# Generated by Django 5.2.6 on 2025-12-26 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financials', '0002_alter_usersubscription_promotional_deal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(db_index=True, help_text='Unique affiliate referral code', max_length=50, unique=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name (if business affiliate)', max_length=255)),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, help_text='Affiliate website or landing page')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Commission percentage (e.g., 20.00 for 20%)', max_digits=5)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('fixed_commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed commission amount (if commission_type is fixed)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this affiliate')),
                ('total_referrals', models.IntegerField(default=0, help_text='Total number of referrals')),
                ('total_conversions', models.IntegerField(default=0, help_text='Total number of conversions')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_commission_pending', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payout_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum amount before payout', max_digits=10)),
                ('payout_method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check')], default='paypal', max_length=50)),
                ('payout_email', models.EmailField(blank=True, help_text='Email for PayPal/Stripe payouts', max_length=254)),
                ('bank_account_details', models.JSONField(blank=True, default=dict, help_text='Encrypted bank account details (JSON)')),
                ('tax_entity_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', help_text='Individual or Business entity', max_length=20)),
                ('tax_id_type', models.CharField(blank=True, choices=[('ssn', 'SSN (Social Security Number)'), ('ein', 'EIN (Employer Identification Number)')], help_text='SSN or EIN', max_length=10)),
                ('tax_id_number', models.CharField(blank=True, help_text='Encrypted SSN or EIN (store encrypted in production)', max_length=50)),
                ('legal_name', models.CharField(blank=True, help_text='Full legal name or business name', max_length=255)),
                ('tax_address_line1', models.CharField(blank=True, max_length=255)),
                ('tax_address_line2', models.CharField(blank=True, max_length=255)),
                ('tax_city', models.CharField(blank=True, max_length=100)),
                ('tax_state', models.CharField(blank=True, max_length=100)),
                ('tax_postal_code', models.CharField(blank=True, max_length=20)),
                ('tax_country', models.CharField(default='US', max_length=100)),
                ('w9_completed', models.BooleanField(default=False, help_text='W-9 form completed')),
                ('w9_completed_at', models.DateTimeField(blank=True, null=True)),
                ('w9_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('current_year_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Earnings in current calendar year', max_digits=10)),
                ('last_1099_year', models.IntegerField(blank=True, help_text='Last year 1099 was issued', null=True)),
                ('last_1099_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount reported on last 1099', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_affiliates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payout_method', models.CharField(help_text='PayPal, Stripe, Bank Transfer, etc.', max_length=50)),
                ('payout_reference', models.CharField(blank=True, help_text='Transaction ID or reference number from payment provider', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(help_text='Start of commission period')),
                ('period_end', models.DateTimeField(help_text='End of commission period')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this payout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='affiliates.affiliate')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate Payout',
                'verbose_name_plural': 'Affiliate Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, help_text='Referral code used (usually affiliate_code)', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer_url', models.URLField(blank=True, help_text='URL that referred the user')),
                ('landing_page', models.URLField(blank=True, help_text='Landing page URL')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed_up', 'Signed Up'), ('converted', 'Converted'), ('expired', 'Expired'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('signed_up_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('cookie_expires_at', models.DateTimeField(blank=True, help_text='When the referral cookie expires (typically 30 days)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='affiliates.affiliate')),
                ('conversion_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_referrals', to='financials.usersubscription')),
                ('referred_user', models.ForeignKey(blank=True, help_text='User who was referred (if signed up)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_amount', models.DecimalField(decimal_places=2, help_text='Amount of subscription that generated commission', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate at time of conversion', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated commission amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this commission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliates.affiliate')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL)),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='affiliates.affiliatepayout')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='financials.usersubscription')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliates.referral')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['affiliate_code'], name='affiliates__affilia_057b24_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['status', '-created_at'], name='affiliates__status_3c7bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['user'], name='affiliates__user_id_f70b06_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatepayout',
            index=models.Index(fields=['affiliate', 'status'], name='affiliates__affilia_78d47e_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatepayout',
            index=models.Index(fields=['status', '-created_at'], name='affiliates__status_6b4e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['affiliate', 'status'], name='affiliates__affilia_ff356e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='affiliates__referra_718b49_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_user', '-created_at'], name='affiliates__referre_b00dce_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', '-created_at'], name='affiliates__status_e0cac8_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['affiliate', 'status'], name='affiliates__affilia_c2b19a_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', '-created_at'], name='affiliates__status_2cc464_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['subscription'], name='affiliates__subscri_98274b_idx'),
        ),
    ]
