# Generated by Django 5.2.6 on 2025-12-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='application_notes',
            field=models.TextField(blank=True, help_text='Notes provided by applicant during sign-up'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the application was rejected', null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_affiliates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
    ]
