# Generated by Django 5.2.6 on 2025-12-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotionaldeal',
            new_name='marketing_p_slug_76c620_idx',
            old_name='marketing_p_slug_is_a_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionaldeal',
            new_name='marketing_p_start_d_7bf341_idx',
            old_name='marketing_p_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionaldeal',
            new_name='marketing_p_feature_693b20_idx',
            old_name='marketing_p_feature_idx',
        ),
    ]
