"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from urllib.parse import urlparse
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# Look for .env file in the backend directory (BASE_DIR)
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Environment variable loading
# Try to use python-decouple if available, otherwise use os.environ
# python-decouple automatically looks for .env file in current directory and parent directories
# When Django runs from backend/, .env should be in backend/ directory
try:
    from decouple import config, Csv
    USE_DECOUPLE = True
except ImportError:
    USE_DECOUPLE = False
    # Fallback function for os.environ
    def config(key, default=None, cast=None):
        value = os.environ.get(key, default)
        if cast is not None and value is not None and value != default:
            try:
                return cast(value)
            except (ValueError, TypeError):
                return default
        return value
    def Csv(value, cast=None):
        if value is None:
            return []
        return [v.strip() for v in value.split(',') if v.strip()]


def get_env_bool(key, default=False):
    """Get boolean environment variable"""
    if USE_DECOUPLE:
        return config(key, default=default, cast=bool)
    value = config(key, default=str(default))
    return value.lower() in ('true', '1', 'yes', 'on')


def get_env_list(key, default=None):
    """Get list environment variable (comma-separated)
    
    Returns a list, ensuring Django's ALLOWED_HOSTS requirement is met.
    Always returns a list (never None, tuple, or other types).
    """
    # Normalize default to a list
    if default is None:
        default_list = []
    elif isinstance(default, (list, tuple)):
        default_list = list(default)
    else:
        default_list = [str(default)]
    
    # Ensure default_list is a list
    if not isinstance(default_list, list):
        default_list = []
    
    # Helper function to ensure result is always a list
    def ensure_list(value, fallback_default):
        """Ensure value is a list, otherwise return fallback_default"""
        if isinstance(value, list):
            return value
        elif isinstance(value, tuple):
            return list(value)
        elif value is None:
            return fallback_default.copy() if fallback_default else []
        else:
            return fallback_default.copy() if fallback_default else []
    
    if USE_DECOUPLE:
        try:
            # Convert default list to comma-separated string for python-decouple
            if default_list:
                default_str = ','.join(str(v) for v in default_list)
            else:
                default_str = ''
            
            # Get value from environment as string first, then parse
            try:
                # Get as string (don't use Csv cast to avoid issues)
                raw_str = config(key, default='')
                # If empty, use default
                if not raw_str or raw_str.strip() == '':
                    return ensure_list(None, default_list)
                # Parse comma-separated string manually
                parsed_list = [v.strip() for v in str(raw_str).split(',') if v.strip()]
                # If parsing results in empty list, use default
                if not parsed_list:
                    return ensure_list(None, default_list)
            except Exception:
                # If config fails, use default
                return ensure_list(None, default_list)
            
            # Filter out empty strings and None values
            filtered_list = [str(v).strip() for v in parsed_list if v is not None and str(v).strip()]
            
            # If filtered list is empty and we have a default, return default
            if not filtered_list and default_list:
                return ensure_list(default_list.copy(), default_list)
            
            # Return filtered list (ensure it's a list)
            return ensure_list(filtered_list, default_list)
            
        except Exception:
            # On any exception, return default as a list
            return ensure_list(None, default_list)
    
    # Fallback to os.environ (when python-decouple is not available)
    try:
        value = config(key, default='')
        if not value or value == '':
            return ensure_list(None, default_list)
        
        # Split comma-separated values
        result = [v.strip() for v in str(value).split(',') if v.strip()]
        if not result:
            return ensure_list(None, default_list)
        return ensure_list(result, default_list)
    except Exception:
        # On any error, return default as a list
        return ensure_list(None, default_list)


def _is_ip_address(hostname: str) -> bool:
    """Return True when hostname is an IPv4 address."""
    parts = hostname.split(".")
    if len(parts) != 4:
        return False
    for part in parts:
        if not part.isdigit():
            return False
        value = int(part)
        if value < 0 or value > 255:
            return False
    return True


def _frontend_origin_variants(url: str) -> list[str]:
    """Build HTTPS/HTTP and www/naked variants for a frontend URL."""
    if not url:
        return []
    parsed = urlparse(url)
    if not parsed.scheme or not parsed.netloc:
        return [url]

    host = parsed.netloc.split(":")[0]
    variants = {url}

    # Add www/naked variant for domains (but not localhost or IPs)
    if host not in ("localhost", "127.0.0.1") and not _is_ip_address(host):
        if host.startswith("www."):
            alt_host = host[4:]
        else:
            alt_host = f"www.{host}"
        variants.add(f"{parsed.scheme}://{alt_host}")

    # Add HTTP/HTTPS variant for each
    expanded = set()
    for origin in variants:
        expanded.add(origin)
        if origin.startswith("https://"):
            expanded.add(origin.replace("https://", "http://", 1))
        elif origin.startswith("http://"):
            expanded.add(origin.replace("http://", "https://", 1))

    return sorted(expanded)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable - REQUIRED in production
SECRET_KEY = config('SECRET_KEY', default='django-insecure-lc*ju4=46*vlq62ladn2_l1tb)h%#roituyojqs#czz^j&^tof')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should be False in production - set via environment variable
DEBUG = get_env_bool('DEBUG', default=True)

# ALLOWED_HOSTS - must be set in production via environment variable
ALLOWED_HOSTS = get_env_list('ALLOWED_HOSTS', default=['18.219.75.17', 'localhost', '127.0.0.1'])

# Frontend URL - used for email verification links and other frontend redirects
# Set via environment variable: FRONTEND_URL=https://pagerodeo.com
# This is also used to auto-configure CSRF_TRUSTED_ORIGINS and CORS_ALLOWED_ORIGINS
FRONTEND_URL = os.getenv("FRONTEND_URL")
NEXT_PUBLIC_APP_URL = os.getenv("NEXT_PUBLIC_APP_URL")  # Alternative name for Next.js compatibility
NEXT_PUBLIC_API_BASE_URL = os.getenv("NEXT_PUBLIC_API_BASE_URL")

# Media (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CSRF_TRUSTED_ORIGINS - required for Django 4.0+ to allow CSRF from these origins
# Set via environment variable as comma-separated list: http://129.146.57.158,https://pagerodeo.com,http://pagerodeo.com
# In production, MUST include your production domain (both HTTP and HTTPS if applicable)
csrf_defaults = ['http://localhost:8000', 'http://127.0.0.1:8000']
# Auto-add production domain from FRONTEND_URL if set
if FRONTEND_URL:
    csrf_defaults.extend(_frontend_origin_variants(FRONTEND_URL))
CSRF_TRUSTED_ORIGINS = get_env_list('CSRF_TRUSTED_ORIGINS', default=csrf_defaults)

# Warn if using insecure defaults
if DEBUG and SECRET_KEY.startswith('django-insecure-'):
    import warnings
    warnings.warn(
        'WARNING: Using insecure SECRET_KEY. Set SECRET_KEY environment variable in production!',
        UserWarning
    )

APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'django_extensions',
    'actstream',
    'auditlog',
    'drf_spectacular',
    'anymail',  # For Amazon SES email backend
    'core.apps.CoreConfig',  # For management commands
    'users',
    'multilocation',
    'multilanguage',
    'financials',
    'marketing',
    'emails',
    'dns',
    'blog',
    'affiliates',
    'site_settings.apps.SettingsConfig',
    'audit_reports',
    'monitoring',
    'performance_analysis',
    'monitor_analysis',
    'dns_analysis',
    'sitemap_analysis',
    'typography_analysis',
    'ssl_analysis',
    'api_analysis',
    'links_analysis',
    'api_monitoring',
    'db_management',
    'collateral',  # Learning Materials (Collateral)
    'security_monitoring',  # Security Monitoring External Testing
    # Compliance Module
    'compliance_frameworks',
    'compliance_controls',
    'compliance_evidence',
    'compliance_policies',
    'compliance_audits',
    'compliance_reports',
    'compliance_tools',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Rate limiting middleware (if django-ratelimit is installed)
    # Note: Rate limiting is applied via decorators in views
    # Custom middleware for logging and monitoring
    'core.middleware.RequestResponseLoggingMiddleware',
    'core.middleware.PerformanceMonitoringMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],  # Add core templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Load database credentials from environment variables
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='opticini'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='127.0.0.1'),  # Use 127.0.0.1 instead of localhost to force IPv4
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# CORS Configuration
# In production, set CORS_ALLOW_ALL_ORIGINS=False and configure CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = get_env_bool('CORS_ALLOW_ALL_ORIGINS', default=True)
cors_defaults = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Auto-add production frontend URL if set
if FRONTEND_URL:
    cors_defaults.extend(_frontend_origin_variants(FRONTEND_URL))
CORS_ALLOWED_ORIGINS = get_env_list('CORS_ALLOWED_ORIGINS', default=cors_defaults)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Email Configuration
# Supports both SMTP (Gmail, etc.) and Amazon SES via django-anymail
# Set EMAIL_BACKEND to 'anymail.backends.amazon_ses.EmailBackend' for SES
# Or use 'django.core.mail.backends.smtp.EmailBackend' for SMTP

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')

# SMTP Configuration (for Gmail, etc.)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = int(config('EMAIL_PORT', default='587'))
EMAIL_USE_TLS = get_env_bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_SSL = False  # Use TLS instead of SSL for port 587
EMAIL_TIMEOUT = 30

# Default FROM email address
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'noreply@pagerodeo.com')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

# Amazon SES Configuration (when using anymail.backends.amazon_ses.EmailBackend)
# AWS credentials can be provided via environment variables or IAM role
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_SES_REGION_NAME = config('AWS_SES_REGION_NAME', default='us-east-1')
AWS_SES_REGION_ENDPOINT = config('AWS_SES_REGION_ENDPOINT', default='')

# Anymail settings for Amazon SES
ANYMAIL = {
    "AMAZON_SES_CLIENT_PARAMS": {
        "region_name": AWS_SES_REGION_NAME,
    }
}

# If AWS credentials are provided, add them to client params
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    ANYMAIL["AMAZON_SES_CLIENT_PARAMS"]["aws_access_key_id"] = AWS_ACCESS_KEY_ID
    ANYMAIL["AMAZON_SES_CLIENT_PARAMS"]["aws_secret_access_key"] = AWS_SECRET_ACCESS_KEY

# If custom endpoint is provided, add it
if AWS_SES_REGION_ENDPOINT:
    ANYMAIL["AMAZON_SES_CLIENT_PARAMS"]["endpoint_url"] = AWS_SES_REGION_ENDPOINT

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directory where collectstatic will gather all static files

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Token Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # 30 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 7 days
    'ROTATE_REFRESH_TOKENS': True,  # Automatically rotate refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old tokens after rotation
    'UPDATE_LAST_LOGIN': True,  # Update last login timestamp
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Opticini API',
    'DESCRIPTION': 'User Management and Performance Testing API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# PostHog Analytics Configuration
# Import PostHog config (will be None if not configured)
try:
    from core.posthog_config import posthog_client, capture_event, identify_user
except ImportError:
    posthog_client = None
    capture_event = lambda *args, **kwargs: None
    identify_user = lambda *args, **kwargs: None

# Centralized Logging Configuration
try:
    from core.logging_config import LOGGING
except ImportError:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    }

# Security Configuration
# Import security settings from security_config.py
try:
    from core.security_config import (
        SECURE_SSL_REDIRECT,
        SECURE_HSTS_SECONDS,
        SECURE_HSTS_INCLUDE_SUBDOMAINS,
        SECURE_HSTS_PRELOAD,
        SECURE_CONTENT_TYPE_NOSNIFF,
        SECURE_BROWSER_XSS_FILTER,
        X_FRAME_OPTIONS,
        SECURE_REFERRER_POLICY,
        SECURE_PROXY_SSL_HEADER,
        SESSION_COOKIE_SECURE,
        SESSION_COOKIE_HTTPONLY,
        SESSION_COOKIE_SAMESITE,
        CSRF_COOKIE_SECURE,
        CSRF_COOKIE_HTTPONLY,
        CSRF_COOKIE_SAMESITE,
        RATE_LIMIT_ENABLE,
        RATE_LIMIT_PER_MINUTE,
        RATE_LIMIT_PER_HOUR,
    )
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = SECURE_HSTS_SECONDS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_INCLUDE_SUBDOMAINS
    SECURE_HSTS_PRELOAD = SECURE_HSTS_PRELOAD
    
    # Security Headers
    SECURE_PROXY_SSL_HEADER = 'HTTP_X_FORWARDED_PROTO', 'https'
    SECURE_CONTENT_TYPE_NOSNIFF = SECURE_CONTENT_TYPE_NOSNIFF
    SECURE_BROWSER_XSS_FILTER = SECURE_BROWSER_XSS_FILTER
    X_FRAME_OPTIONS = X_FRAME_OPTIONS
    SECURE_REFERRER_POLICY = SECURE_REFERRER_POLICY
    
    # Proxy SSL Header (if behind reverse proxy)
    # Must be a tuple of (header_name, header_value) for Django
    if SECURE_PROXY_SSL_HEADER:
        # Convert to tuple if it's a list or Csv object
        if isinstance(SECURE_PROXY_SSL_HEADER, (list, tuple)) or hasattr(SECURE_PROXY_SSL_HEADER, '__iter__'):
            if not isinstance(SECURE_PROXY_SSL_HEADER, str):
                SECURE_PROXY_SSL_HEADER = tuple(SECURE_PROXY_SSL_HEADER)
                # Ensure it has exactly 2 elements
                if len(SECURE_PROXY_SSL_HEADER) != 2:
                    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Secure Cookies
    SESSION_COOKIE_SECURE = SESSION_COOKIE_SECURE
    SESSION_COOKIE_HTTPONLY = SESSION_COOKIE_HTTPONLY
    SESSION_COOKIE_SAMESITE = SESSION_COOKIE_SAMESITE
    CSRF_COOKIE_SECURE = CSRF_COOKIE_SECURE
    CSRF_COOKIE_HTTPONLY = CSRF_COOKIE_HTTPONLY
    CSRF_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE
    
    # Rate Limiting Settings
    RATE_LIMIT_ENABLE = RATE_LIMIT_ENABLE
    RATE_LIMIT_PER_MINUTE = RATE_LIMIT_PER_MINUTE
    RATE_LIMIT_PER_HOUR = RATE_LIMIT_PER_HOUR
    
except ImportError:
    # Fallback security settings if security_config.py is not available
    # These are production-safe defaults
    SECURE_SSL_REDIRECT = not DEBUG
    SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
    SECURE_HSTS_PRELOAD = not DEBUG
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # Secure Cookies - Allow override via environment for proxy/load balancer setups
    # If behind a proxy that doesn't properly set X-Forwarded-Proto, you may need to set these to False
    # Or configure your proxy to set X-Forwarded-Proto header correctly
    SESSION_COOKIE_SECURE = get_env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = get_env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # Proxy SSL Header - Set this if behind a reverse proxy/load balancer
    # Format: HTTP_X_FORWARDED_PROTO,https
    proxy_header = config('SECURE_PROXY_SSL_HEADER', default='')
    if proxy_header:
        # Parse comma-separated value: "HTTP_X_FORWARDED_PROTO,https"
        parts = [p.strip() for p in proxy_header.split(',')]
        if len(parts) == 2:
            SECURE_PROXY_SSL_HEADER = tuple(parts)
        else:
            SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    else:
        SECURE_PROXY_SSL_HEADER = None
    
    RATE_LIMIT_ENABLE = True
    RATE_LIMIT_PER_MINUTE = 60
    RATE_LIMIT_PER_HOUR = 1000

# Content Security Policy (CSP)
# Note: django-csp is not installed by default
# To enable CSP, install: pip install django-csp
# Then add 'csp' to INSTALLED_APPS and 'csp.middleware.CSPMiddleware' to MIDDLEWARE
try:
    import csp
    # CSP is available
    CSP_ENABLED = True
except ImportError:
    CSP_ENABLED = False
    # CSP settings (will be ignored if django-csp is not installed)
    CSP_DEFAULT_SRC = ["'self'"]
    CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
    CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]
    CSP_IMG_SRC = ["'self'", 'data:', 'https:']
    CSP_FONT_SRC = ["'self'", 'data:']
    CSP_CONNECT_SRC = ["'self'"]
    CSP_FRAME_SRC = ["'self'"]

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Celery Task Settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Windows-specific: Use 'solo' pool instead of 'prefork' (multiprocessing doesn't work well on Windows)
import sys
if sys.platform == 'win32':
    CELERY_WORKER_POOL = 'solo'  # Single-process pool for Windows compatibility