# Generated by Django 5.2.6 on 2025-11-25 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_reports', '0002_rename_audit_repor_user_id_a1b2c3_idx_audit_repor_user_id_dda0b8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='URL that was analyzed', max_length=2048)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('checking', 'Checking')], help_text='Current status of the page', max_length=16)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('response_time', models.IntegerField(db_index=True, help_text='Response time in milliseconds')),
                ('ssl_valid', models.BooleanField(blank=True, help_text='Whether SSL certificate is valid (for HTTPS URLs)', null=True)),
                ('ssl_expires_in', models.IntegerField(blank=True, help_text='Days until SSL certificate expires', null=True)),
                ('ssl_issuer', models.CharField(blank=True, help_text='SSL certificate issuer', max_length=255)),
                ('server', models.CharField(blank=True, help_text='Server header value', max_length=255)),
                ('content_type', models.CharField(blank=True, help_text='Content-Type header value', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error message if check failed')),
                ('uptime_percentage', models.FloatField(blank=True, help_text='Uptime percentage over the tracking period', null=True)),
                ('total_checks', models.IntegerField(blank=True, help_text='Total number of checks performed', null=True)),
                ('successful_checks', models.IntegerField(blank=True, help_text='Number of successful checks', null=True)),
                ('failed_checks', models.IntegerField(blank=True, help_text='Number of failed checks', null=True)),
                ('avg_response_time', models.FloatField(blank=True, help_text='Average response time over tracking period (ms)', null=True)),
                ('min_response_time', models.IntegerField(blank=True, help_text='Minimum response time (ms)', null=True)),
                ('max_response_time', models.IntegerField(blank=True, help_text='Maximum response time (ms)', null=True)),
                ('health_score', models.IntegerField(blank=True, help_text='Overall health score (0-100)', null=True)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of issues found')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of recommendations')),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete monitor analysis results')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('audit_report', models.ForeignKey(blank=True, help_text='Audit report this analysis belongs to (if part of full audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_analyses', to='audit_reports.auditreport')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitor Analysis',
                'verbose_name_plural': 'Monitor Analyses',
                'db_table': 'monitor_analysis',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='monitor_ana_url_fa38c8_idx'), models.Index(fields=['user', '-analyzed_at'], name='monitor_ana_user_id_19b48b_idx'), models.Index(fields=['audit_report', '-analyzed_at'], name='monitor_ana_audit_r_cd5870_idx'), models.Index(fields=['status', '-analyzed_at'], name='monitor_ana_status_cad5d8_idx'), models.Index(fields=['response_time'], name='monitor_ana_respons_dcfb55_idx')],
            },
        ),
    ]
