# Generated by Django 5.2.6 on 2026-01-04 21:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Framework name (e.g., SOC 2 Type I)', max_length=200)),
                ('code', models.CharField(help_text='Framework code (e.g., SOC2-T1)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('security', 'Security'), ('privacy', 'Privacy'), ('industry', 'Industry'), ('regional', 'Regional')], help_text='Framework category', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Framework description')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='Whether framework is enabled for this organization')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('at_risk', 'At Risk'), ('not_started', 'Not Started')], default='not_started', help_text='Readiness status', max_length=20)),
                ('compliance_score', models.IntegerField(default=0, help_text='Compliance score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_controls', models.IntegerField(default=0, help_text='Total number of controls in this framework')),
                ('passing_controls', models.IntegerField(default=0, help_text='Number of passing controls')),
                ('failing_controls', models.IntegerField(default=0, help_text='Number of failing controls')),
                ('not_evaluated_controls', models.IntegerField(default=0, help_text='Number of controls not yet evaluated')),
                ('last_evaluated', models.DateTimeField(blank=True, help_text='Last evaluation date', null=True)),
                ('next_audit_date', models.DateTimeField(blank=True, help_text='Next scheduled audit date', null=True)),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization/tenant ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_frameworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Framework',
                'verbose_name_plural': 'Compliance Frameworks',
                'db_table': 'compliance_frameworks',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='compliance__code_c2136e_idx'), models.Index(fields=['category', 'status'], name='compliance__categor_28df45_idx'), models.Index(fields=['enabled', 'status'], name='compliance__enabled_0e35b0_idx'), models.Index(fields=['organization_id'], name='compliance__organiz_981567_idx')],
            },
        ),
    ]
