# Generated by Django 5.2.6 on 2025-11-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField(blank=True, help_text='Hour of day (0-23) for hourly aggregates, null for daily', null=True)),
                ('avg_score', models.FloatField(help_text='Average performance score')),
                ('min_score', models.IntegerField(help_text='Minimum performance score')),
                ('max_score', models.IntegerField(help_text='Maximum performance score')),
                ('avg_lcp', models.FloatField(help_text='Average LCP (seconds)')),
                ('avg_fid', models.FloatField(help_text='Average FID (milliseconds)')),
                ('avg_cls', models.FloatField(help_text='Average CLS')),
                ('avg_page_size_mb', models.FloatField(blank=True, null=True)),
                ('avg_request_count', models.FloatField(blank=True, null=True)),
                ('avg_load_time', models.FloatField(blank=True, null=True)),
                ('analysis_count', models.IntegerField(help_text='Number of analyses in this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Performance History',
                'verbose_name_plural': 'Performance Histories',
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['url', 'device', '-date'], name='performance_url_f2fa59_idx')],
                'unique_together': {('url', 'device', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='URL that was analyzed', max_length=2048)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', help_text='Device type used for analysis', max_length=10)),
                ('performance_score', models.IntegerField(db_index=True, help_text='Lighthouse performance score (0-100)')),
                ('lcp', models.FloatField(db_index=True, help_text='Largest Contentful Paint (seconds)')),
                ('fid', models.FloatField(db_index=True, help_text='First Input Delay (milliseconds)')),
                ('cls', models.FloatField(db_index=True, help_text='Cumulative Layout Shift')),
                ('tti', models.FloatField(blank=True, help_text='Time to Interactive (seconds)', null=True)),
                ('tbt', models.FloatField(blank=True, help_text='Total Blocking Time (milliseconds)', null=True)),
                ('fcp', models.FloatField(blank=True, help_text='First Contentful Paint (seconds)', null=True)),
                ('speed_index', models.FloatField(blank=True, help_text='Speed Index (seconds)', null=True)),
                ('page_size_mb', models.FloatField(blank=True, db_index=True, help_text='Total page size in MB', null=True)),
                ('request_count', models.IntegerField(blank=True, help_text='Number of HTTP requests', null=True)),
                ('load_time', models.FloatField(blank=True, help_text='Total load time in seconds', null=True)),
                ('dom_content_loaded', models.FloatField(blank=True, help_text='DOM Content Loaded time (ms)', null=True)),
                ('first_paint', models.FloatField(blank=True, help_text='First Paint time (ms)', null=True)),
                ('accessibility_score', models.IntegerField(blank=True, help_text='Lighthouse accessibility score (0-100)', null=True)),
                ('best_practices_score', models.IntegerField(blank=True, help_text='Lighthouse best practices score (0-100)', null=True)),
                ('seo_score', models.IntegerField(blank=True, help_text='Lighthouse SEO score (0-100)', null=True)),
                ('resources', models.JSONField(blank=True, default=list, help_text='List of resources with size, type, load time')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of performance recommendations')),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete Lighthouse results JSON')),
                ('is_baseline', models.BooleanField(default=False, help_text='True if this is marked as a baseline for comparison')),
                ('score_change', models.IntegerField(blank=True, help_text='Change in performance score from previous analysis', null=True)),
                ('lcp_change', models.FloatField(blank=True, help_text='Change in LCP from previous analysis (seconds)', null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('baseline_id', models.ForeignKey(blank=True, help_text='Reference to baseline analysis for comparison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons', to='performance_analysis.performanceanalysis')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Analysis',
                'verbose_name_plural': 'Performance Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='performance_url_384007_idx'), models.Index(fields=['url', 'device', '-analyzed_at'], name='performance_url_b5a446_idx'), models.Index(fields=['user', '-analyzed_at'], name='performance_user_id_bc98eb_idx'), models.Index(fields=['performance_score'], name='performance_perform_bc8b50_idx'), models.Index(fields=['lcp'], name='performance_lcp_29fd79_idx'), models.Index(fields=['-analyzed_at'], name='performance_analyze_478fb6_idx')],
            },
        ),
    ]
