# Generated by Django 5.2.6 on 2025-11-22 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0002_rename_audit_repor_user_id_a1b2c3_idx_audit_repor_user_id_dda0b8_idx_and_more'),
        ('performance_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceanalysis',
            name='audit_report',
            field=models.ForeignKey(blank=True, help_text='Audit report this analysis belongs to (if part of full audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_analyses', to='audit_reports.auditreport'),
        ),
        migrations.AddIndex(
            model_name='performanceanalysis',
            index=models.Index(fields=['audit_report', '-analyzed_at'], name='performance_audit_r_4c39e1_idx'),
        ),
    ]
