# Generated by Django 5.2.6 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analysis', '0002_performanceanalysis_audit_report_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='performanceanalysis',
            new_name='performance_url_f49e26_idx',
            old_name='performance_url_384007_idx',
        ),
        migrations.RenameIndex(
            model_name='performanceanalysis',
            new_name='performance_url_a1472c_idx',
            old_name='performance_url_b5a446_idx',
        ),
        migrations.RenameIndex(
            model_name='performanceanalysis',
            new_name='performance_user_id_7ee417_idx',
            old_name='performance_user_id_bc98eb_idx',
        ),
        migrations.RenameIndex(
            model_name='performanceanalysis',
            new_name='performance_audit_r_3e56f5_idx',
            old_name='performance_audit_r_4c39e1_idx',
        ),
        migrations.RenameIndex(
            model_name='performanceanalysis',
            new_name='performance_perform_e0ea90_idx',
            old_name='performance_perform_bc8b50_idx',
        ),
        migrations.RenameIndex(
            model_name='performanceanalysis',
            new_name='performance_lcp_afe7df_idx',
            old_name='performance_lcp_29fd79_idx',
        ),
        migrations.RenameIndex(
            model_name='performanceanalysis',
            new_name='performance_analyze_101dca_idx',
            old_name='performance_analyze_478fb6_idx',
        ),
        migrations.RenameIndex(
            model_name='performancehistory',
            new_name='performance_url_e718e4_idx',
            old_name='performance_url_f2fa59_idx',
        ),
        migrations.AlterModelTable(
            name='performanceanalysis',
            table='performance_analysis',
        ),
        migrations.AlterModelTable(
            name='performancehistory',
            table='performance_history',
        ),
    ]
