# Generated by Django 5.2.6 on 2025-11-24 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analysis', '0003_rename_performance_url_384007_idx_performance_url_f49e26_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('resource_type', models.CharField(help_text='document, script, stylesheet, image, font, etc.', max_length=50)),
                ('transfer_size', models.IntegerField(help_text='Actual bytes transferred (compressed)')),
                ('resource_size', models.IntegerField(help_text='Uncompressed resource size')),
                ('compression_ratio', models.FloatField(blank=True, help_text='Compression ratio', null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, help_text='http/1.1, http/2, h3, etc.', max_length=20, null=True)),
                ('start_time', models.FloatField(help_text='Request start time (ms)')),
                ('end_time', models.FloatField(help_text='Request end time (ms)')),
                ('duration', models.FloatField(help_text='Total duration (ms)')),
                ('dns_time', models.FloatField(blank=True, help_text='DNS lookup time (ms)', null=True)),
                ('ssl_time', models.FloatField(blank=True, help_text='SSL negotiation time (ms)', null=True)),
                ('connect_time', models.FloatField(blank=True, help_text='TCP connect time (ms)', null=True)),
                ('send_time', models.FloatField(blank=True, help_text='Request send time (ms)', null=True)),
                ('wait_time', models.FloatField(blank=True, help_text='Server wait time (ms)', null=True)),
                ('receive_time', models.FloatField(blank=True, help_text='Response receive time (ms)', null=True)),
                ('priority', models.CharField(blank=True, help_text='High, Medium, Low, VeryLow', max_length=20, null=True)),
                ('render_blocking_status', models.CharField(blank=True, help_text='blocking, non-blocking, potentially-blocking', max_length=50, null=True)),
                ('initiator_type', models.CharField(blank=True, help_text='parser, script, preload, etc.', max_length=50, null=True)),
                ('initiator_url', models.URLField(blank=True, help_text='URL that initiated this request', max_length=2048, null=True)),
                ('from_cache', models.BooleanField(default=False)),
                ('from_service_worker', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(help_text='Order in which request was made (for waterfall)')),
                ('performance_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_requests', to='performance_analysis.performanceanalysis')),
            ],
            options={
                'verbose_name': 'Network Request',
                'verbose_name_plural': 'Network Requests',
                'db_table': 'network_request',
                'ordering': ['performance_analysis', 'sequence', 'start_time'],
                'indexes': [models.Index(fields=['performance_analysis', 'start_time'], name='network_req_perform_a92f6b_idx'), models.Index(fields=['performance_analysis', 'resource_type'], name='network_req_perform_e466fd_idx'), models.Index(fields=['url', '-start_time'], name='network_req_url_5f62dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Event name', max_length=255)),
                ('category', models.CharField(choices=[('navigation', 'Navigation'), ('paint', 'Paint'), ('measure', 'Measure'), ('mark', 'Mark'), ('script', 'Script'), ('layout', 'Layout'), ('other', 'Other')], db_index=True, max_length=20)),
                ('timestamp', models.FloatField(help_text='Event timestamp (microseconds)')),
                ('duration', models.FloatField(blank=True, help_text='Event duration (microseconds)', null=True)),
                ('phase', models.CharField(choices=[('B', 'Begin'), ('E', 'End'), ('I', 'Instant'), ('X', 'Complete')], help_text='Event phase', max_length=1)),
                ('sequence', models.IntegerField(help_text='Order in timeline')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional event data')),
                ('performance_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='performance_analysis.performanceanalysis')),
            ],
            options={
                'verbose_name': 'Performance Timeline Event',
                'verbose_name_plural': 'Performance Timeline Events',
                'db_table': 'performance_timeline_event',
                'ordering': ['performance_analysis', 'timestamp', 'sequence'],
                'indexes': [models.Index(fields=['performance_analysis', 'timestamp'], name='performance_perform_166cfe_idx'), models.Index(fields=['performance_analysis', 'category'], name='performance_perform_7df6d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('resource_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('document', 'Document'), ('script', 'Script'), ('stylesheet', 'Stylesheet'), ('image', 'Image'), ('font', 'Font'), ('media', 'Media'), ('other', 'Other')], db_index=True, max_length=20)),
                ('transfer_size', models.IntegerField(help_text='Compressed size (bytes)')),
                ('resource_size', models.IntegerField(help_text='Uncompressed size (bytes)')),
                ('gzip_savings', models.IntegerField(blank=True, help_text='Bytes saved by compression', null=True)),
                ('render_blocking', models.BooleanField(db_index=True, default=False, help_text='Is this resource render-blocking?')),
                ('unused_css', models.BooleanField(default=False, help_text='Is unused CSS detected?')),
                ('unused_javascript', models.BooleanField(default=False, help_text='Is unused JavaScript detected?')),
                ('can_minify', models.BooleanField(default=False, help_text='Can this resource be minified?')),
                ('can_compress', models.BooleanField(default=False, help_text='Can this resource be compressed?')),
                ('can_cache', models.BooleanField(default=False, help_text='Can this resource be cached?')),
                ('load_time', models.FloatField(blank=True, help_text='Resource load time (ms)', null=True)),
                ('performance_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_breakdowns', to='performance_analysis.performanceanalysis')),
            ],
            options={
                'verbose_name': 'Resource Breakdown',
                'verbose_name_plural': 'Resource Breakdowns',
                'db_table': 'resource_breakdown',
                'ordering': ['performance_analysis', '-transfer_size'],
                'indexes': [models.Index(fields=['performance_analysis', 'category'], name='resource_br_perform_afa032_idx'), models.Index(fields=['performance_analysis', 'render_blocking'], name='resource_br_perform_fffdd3_idx')],
            },
        ),
    ]
