# Generated by Django 5.2.6 on 2025-11-24 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0002_rename_audit_repor_user_id_a1b2c3_idx_audit_repor_user_id_dda0b8_idx_and_more'),
        ('performance_analysis', '0004_networkrequest_performancetimelineevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkrequest',
            name='audit_report',
            field=models.ForeignKey(blank=True, help_text='Direct link to audit report for easier querying', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_requests', to='audit_reports.auditreport'),
        ),
        migrations.AddField(
            model_name='performancetimelineevent',
            name='audit_report',
            field=models.ForeignKey(blank=True, help_text='Direct link to audit report for easier querying', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='audit_reports.auditreport'),
        ),
        migrations.AddField(
            model_name='resourcebreakdown',
            name='audit_report',
            field=models.ForeignKey(blank=True, help_text='Direct link to audit report for easier querying', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_breakdowns', to='audit_reports.auditreport'),
        ),
    ]
