# Generated by Django 5.2.6 on 2025-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analysis', '0006_add_missing_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetimelineevent',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional event data (args from traceEvents)'),
        ),
    ]
