# Generated by Django 5.2.6 on 2025-11-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypographyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Page URL that was analyzed', max_length=2048)),
                ('fonts_used', models.JSONField(blank=True, default=list, help_text='List of fonts used on the page')),
                ('font_sizes', models.JSONField(blank=True, default=list, help_text='List of font sizes found')),
                ('font_weights', models.JSONField(blank=True, default=list, help_text='List of font weights used')),
                ('line_heights', models.JSONField(blank=True, default=list, help_text='List of line heights used')),
                ('font_families', models.JSONField(blank=True, default=list, help_text='List of font families used')),
                ('total_fonts', models.IntegerField(blank=True, help_text='Total number of unique fonts used', null=True)),
                ('total_font_sizes', models.IntegerField(blank=True, help_text='Total number of unique font sizes', null=True)),
                ('min_font_size', models.FloatField(blank=True, help_text='Minimum font size (px)', null=True)),
                ('max_font_size', models.FloatField(blank=True, help_text='Maximum font size (px)', null=True)),
                ('avg_font_size', models.FloatField(blank=True, help_text='Average font size (px)', null=True)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of typography issues found (e.g., too many fonts, small text)')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of typography recommendations')),
                ('health_score', models.IntegerField(blank=True, help_text='Typography health score (0-100)', null=True)),
                ('accessibility_issues', models.JSONField(blank=True, default=list, help_text='Typography-related accessibility issues')),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete typography analysis results')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typography_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typography Analysis',
                'verbose_name_plural': 'Typography Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='typography__url_1ed490_idx'), models.Index(fields=['user', '-analyzed_at'], name='typography__user_id_5e3e39_idx')],
            },
        ),
    ]
