# Generated by Django 5.2.6 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typography_analysis', '0002_typographyanalysis_audit_report_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='typographyanalysis',
            new_name='typography__url_2f4bb4_idx',
            old_name='typography__url_1ed490_idx',
        ),
        migrations.RenameIndex(
            model_name='typographyanalysis',
            new_name='typography__user_id_ed449d_idx',
            old_name='typography__user_id_5e3e39_idx',
        ),
        migrations.RenameIndex(
            model_name='typographyanalysis',
            new_name='typography__audit_r_28692a_idx',
            old_name='typography__audit_r_846ca5_idx',
        ),
        migrations.AlterModelTable(
            name='typographyanalysis',
            table='typography_analysis',
        ),
    ]
