# Generated by Django 5.2.6 on 2025-10-30 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Palette name (e.g., 'Ocean Blue', 'Forest Green')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this color palette')),
                ('primary_color', models.CharField(default='#0086ad', help_text='Primary brand color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #0086ad)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('secondary_color', models.CharField(default='#005582', help_text='Secondary brand color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #0086ad)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('accent_1', models.CharField(default='#00c2c7', help_text='First accent color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #0086ad)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('accent_2', models.CharField(default='#97ebdb', help_text='Second accent color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #0086ad)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('accent_3', models.CharField(default='#daf8e3', help_text='Third accent color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #0086ad)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('is_active', models.BooleanField(default=False, help_text='Only one palette can be active at a time')),
                ('is_system', models.BooleanField(default=False, help_text='System palettes cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_palettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme Palette',
                'verbose_name_plural': 'Theme Palettes',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypographyPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Preset name (e.g., 'Compact', 'Comfortable', 'Large')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this typography preset')),
                ('body_font', models.CharField(default='Inter, system-ui, -apple-system, sans-serif', help_text='Font family for body text', max_length=200)),
                ('heading_font', models.CharField(default='Inter, system-ui, -apple-system, sans-serif', help_text='Font family for all headings (H1-H6)', max_length=200)),
                ('font_size_base', models.CharField(default='16px', help_text='Base font size for body text', max_length=10)),
                ('font_size_h1', models.CharField(default='48px', help_text='H1 heading size', max_length=10)),
                ('font_size_h2', models.CharField(default='36px', help_text='H2 heading size', max_length=10)),
                ('font_size_h3', models.CharField(default='30px', help_text='H3 heading size', max_length=10)),
                ('font_size_h4', models.CharField(default='24px', help_text='H4 heading size', max_length=10)),
                ('font_size_h5', models.CharField(default='20px', help_text='H5 heading size', max_length=10)),
                ('font_size_h6', models.CharField(default='18px', help_text='H6 heading size', max_length=10)),
                ('line_height_base', models.CharField(default='1.6', help_text='Base line height (unitless or percentage)', max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='Only one preset can be active at a time')),
                ('is_system', models.BooleanField(default=False, help_text='System presets cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_typography_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typography Preset',
                'verbose_name_plural': 'Typography Presets',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PageRodeo', help_text='Site name displayed in header and emails', max_length=100)),
                ('site_description', models.TextField(default='A comprehensive web performance monitoring and analysis platform', help_text='Site description for meta tags')),
                ('default_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='Default language for the application', max_length=5)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', help_text='Default theme mode (light/dark/auto)', max_length=10)),
                ('session_timeout_minutes', models.IntegerField(default=30, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Maximum failed login attempts before lockout')),
                ('require_strong_passwords', models.BooleanField(default=True, help_text='Enforce password complexity requirements')),
                ('enable_two_factor', models.BooleanField(default=False, help_text='Require 2FA for admin accounts')),
                ('enable_email_verification', models.BooleanField(default=False, help_text='Require email verification on registration')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Send notifications via email')),
                ('enable_push_notifications', models.BooleanField(default=True, help_text='Send browser push notifications')),
                ('enable_sms_notifications', models.BooleanField(default=False, help_text='Send notifications via SMS')),
                ('notification_email', models.EmailField(default='admin@pagerodeo.com', help_text='Email address for system notifications', max_length=254)),
                ('api_base_url', models.URLField(default='http://localhost:8000', help_text='Base URL for API endpoints')),
                ('api_rate_limit', models.IntegerField(default=1000, help_text='API rate limit (requests per minute)')),
                ('enable_cors', models.BooleanField(default=True, help_text='Allow cross-origin requests')),
                ('enable_api_docs', models.BooleanField(default=True, help_text='Expose API documentation endpoint')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
                ('active_palette', models.ForeignKey(blank=True, help_text='Currently active color palette', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_config', to='site_settings.themepalette')),
                ('active_typography', models.ForeignKey(blank=True, help_text='Currently active typography preset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_config', to='site_settings.typographypreset')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
