# Generated by Django 5.2.6 on 2025-11-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='enable_analytics',
            field=models.BooleanField(default=False, help_text='Enable client-side analytics (PostHog) in production'),
        ),
    ]
