# Generated by Django 5.2.6 on 2026-01-04 21:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_id', models.CharField(help_text='Policy ID (e.g., POL-001, SEC-001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Policy name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Policy description')),
                ('type', models.CharField(choices=[('security', 'Security'), ('data_retention', 'Data Retention'), ('incident_response', 'Incident Response'), ('ai_governance', 'AI Governance'), ('vendor_risk', 'Vendor Risk'), ('custom', 'Custom')], help_text='Policy type', max_length=30)),
                ('category', models.CharField(blank=True, help_text='Custom category if type is custom', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('needs_review', 'Needs Review'), ('archived', 'Archived')], default='draft', help_text='Policy status', max_length=20)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', help_text='Approval status', max_length=20)),
                ('version', models.CharField(default='1.0', help_text='Current version (e.g., 1.0, 2.3)', max_length=20)),
                ('current_version_id', models.UUIDField(blank=True, help_text='Current version ID', null=True)),
                ('generation_method', models.CharField(choices=[('auto_generated', 'Auto Generated'), ('manual', 'Manual'), ('template_based', 'Template Based')], default='manual', help_text='Generation method', max_length=20)),
                ('generated_from', models.JSONField(blank=True, default=dict, help_text='What this policy was generated from (configs, evidence, controls, etc.)')),
                ('last_generated', models.DateTimeField(blank=True, help_text='Last generation date', null=True)),
                ('sync_status', models.CharField(choices=[('in_sync', 'In Sync'), ('out_of_sync', 'Out of Sync'), ('unknown', 'Unknown')], default='unknown', help_text='Sync status with reality', max_length=20)),
                ('last_sync_check', models.DateTimeField(blank=True, help_text='Last sync check date', null=True)),
                ('sync_issues', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='List of sync issues/mismatches', size=None)),
                ('content', models.TextField(help_text='Full policy text content')),
                ('summary', models.TextField(blank=True, help_text='Executive summary')),
                ('sections', models.JSONField(blank=True, default=list, help_text='Policy sections (structured content)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Approval date', null=True)),
                ('effective_date', models.DateTimeField(blank=True, help_text='Effective date', null=True)),
                ('review_date', models.DateTimeField(blank=True, help_text='Next scheduled review date', null=True)),
                ('evidence_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Related evidence IDs', size=None)),
                ('control_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Related control IDs', size=None)),
                ('export_formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Available export formats', size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Policy tags', size=None)),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization/tenant ID', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('co_owners', models.ManyToManyField(blank=True, help_text='Co-owners', related_name='co_owned_policies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, help_text='User or system that generated this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_policies', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Policy owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Policy',
                'verbose_name_plural': 'Compliance Policies',
                'db_table': 'compliance_policies',
                'ordering': ['policy_id'],
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicyAttestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, help_text='User role at time of attestation', max_length=50)),
                ('acknowledged', models.BooleanField(default=True, help_text='Whether user acknowledged the policy')),
                ('comments', models.TextField(blank=True, help_text='User comments')),
                ('attested_at', models.DateTimeField(auto_now_add=True, help_text='Attestation date')),
                ('policy', models.ForeignKey(help_text='Policy being attested', on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='compliance_policies.compliancepolicy')),
                ('user', models.ForeignKey(help_text='User who attested', on_delete=django.db.models.deletion.CASCADE, related_name='policy_attestations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_policy_attestations',
                'ordering': ['-attested_at'],
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicyFrameworkMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework_id', models.UUIDField(help_text='Framework ID (references compliance_frameworks)')),
                ('framework_name', models.CharField(help_text='Framework name for display', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(help_text='Policy being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='compliance_policies.compliancepolicy')),
            ],
            options={
                'db_table': 'compliance_policy_framework_mappings',
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='Version number (e.g., 1.0, 2.3)', max_length=20)),
                ('content', models.TextField(help_text='Policy content for this version')),
                ('summary', models.TextField(blank=True, help_text='Version summary')),
                ('changes', models.TextField(blank=True, help_text='Changelog for this version')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Approval date', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Policy this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='compliance_policies.compliancepolicy')),
            ],
            options={
                'db_table': 'compliance_policy_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compliancepolicy',
            index=models.Index(fields=['policy_id'], name='compliance__policy__d6895d_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicy',
            index=models.Index(fields=['type', 'status'], name='compliance__type_fbdfa5_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicy',
            index=models.Index(fields=['sync_status'], name='compliance__sync_st_98c032_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicy',
            index=models.Index(fields=['approval_status'], name='compliance__approva_42b559_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicy',
            index=models.Index(fields=['organization_id'], name='compliance__organiz_fca3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicyattestation',
            index=models.Index(fields=['policy', 'user'], name='compliance__policy__4f3ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicyattestation',
            index=models.Index(fields=['attested_at'], name='compliance__atteste_c0f8b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancepolicyattestation',
            unique_together={('policy', 'user')},
        ),
        migrations.AddIndex(
            model_name='compliancepolicyframeworkmapping',
            index=models.Index(fields=['framework_id'], name='compliance__framewo_af787c_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicyframeworkmapping',
            index=models.Index(fields=['policy', 'framework_id'], name='compliance__policy__85a1e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancepolicyframeworkmapping',
            unique_together={('policy', 'framework_id')},
        ),
        migrations.AddIndex(
            model_name='compliancepolicyversion',
            index=models.Index(fields=['policy', 'is_current'], name='compliance__policy__bedbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancepolicyversion',
            index=models.Index(fields=['policy', 'version'], name='compliance__policy__6f6df1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancepolicyversion',
            unique_together={('policy', 'version')},
        ),
    ]
