# Generated by Django 5.2.6 on 2025-12-11 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTranslationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_route', models.CharField(help_text='Page route (e.g., /workspace/users)', max_length=500, unique=True)),
                ('component_path', models.CharField(help_text='Component file path (e.g., studio/app/workspace/users/page.tsx)', max_length=500)),
                ('page_type', models.CharField(choices=[('public', 'Public'), ('workspace', 'Workspace'), ('admin', 'Admin'), ('dashboard', 'Dashboard'), ('component', 'Component'), ('api', 'API')], default='workspace', max_length=20)),
                ('status', models.CharField(choices=[('implemented', 'Implemented'), ('partial', 'Partial'), ('not-implemented', 'Not Implemented')], default='not-implemented', max_length=20)),
                ('auto_discovered', models.BooleanField(default=True, help_text='Whether this page was auto-discovered')),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Last time the page was checked')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the status was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about translation status')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_translation_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Translation Status',
                'verbose_name_plural': 'Page Translation Statuses',
                'ordering': ['page_type', 'page_route'],
                'indexes': [models.Index(fields=['page_route'], name='multilangua_page_ro_73857b_idx'), models.Index(fields=['status'], name='multilangua_status_f02f61_idx'), models.Index(fields=['page_type'], name='multilangua_page_ty_0c0cda_idx')],
            },
        ),
    ]
