# Generated by Django 5.2.6 on 2026-01-04 21:31

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_id', models.CharField(help_text='Audit ID (e.g., AUD-001, SOC2-2024-Q2)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Audit name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Audit description')),
                ('type', models.CharField(choices=[('soc2_readiness', 'SOC 2 Readiness'), ('external_audit', 'External Audit'), ('internal_audit', 'Internal Audit'), ('customer_security_review', 'Customer Security Review'), ('annual_review', 'Annual Review')], help_text='Audit type', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Audit status', max_length=20)),
                ('start_date', models.DateTimeField(help_text='Audit start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Audit end date', null=True)),
                ('scheduled_start_date', models.DateTimeField(blank=True, help_text='Scheduled start date', null=True)),
                ('scheduled_end_date', models.DateTimeField(blank=True, help_text='Scheduled end date', null=True)),
                ('evidence_locked', models.BooleanField(default=False, help_text='Whether evidence is locked for this audit')),
                ('evidence_freeze_date', models.DateTimeField(blank=True, help_text='When evidence was frozen', null=True)),
                ('evidence_count', models.IntegerField(default=0, help_text='Number of evidence items')),
                ('evidence_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Locked evidence IDs', size=None)),
                ('total_controls', models.IntegerField(default=0, help_text='Total number of controls')),
                ('controls_passed', models.IntegerField(default=0, help_text='Number of controls passed')),
                ('controls_failed', models.IntegerField(default=0, help_text='Number of controls failed')),
                ('controls_partial', models.IntegerField(default=0, help_text='Number of controls partially compliant')),
                ('controls_not_evaluated', models.IntegerField(default=0, help_text='Number of controls not evaluated')),
                ('compliance_score', models.IntegerField(blank=True, help_text='Compliance score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('findings_count', models.IntegerField(default=0, help_text='Total number of findings')),
                ('critical_findings', models.IntegerField(default=0, help_text='Number of critical findings')),
                ('high_findings', models.IntegerField(default=0, help_text='Number of high findings')),
                ('medium_findings', models.IntegerField(default=0, help_text='Number of medium findings')),
                ('low_findings', models.IntegerField(default=0, help_text='Number of low findings')),
                ('notes', models.TextField(blank=True, help_text='Audit notes')),
                ('summary', models.TextField(blank=True, help_text='Audit summary')),
                ('conclusion', models.TextField(blank=True, help_text='Audit conclusion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Completion date', null=True)),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization/tenant ID', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audits', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Audit owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_audits', to=settings.AUTH_USER_MODEL)),
                ('previous_audit', models.ForeignKey(blank=True, help_text='Previous audit in sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_audits', to='compliance_audits.complianceaudit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Audit',
                'verbose_name_plural': 'Compliance Audits',
                'db_table': 'compliance_audits',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditAuditor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Auditor name', max_length=200)),
                ('email', models.EmailField(help_text='Auditor email', max_length=254)),
                ('role', models.CharField(choices=[('lead_auditor', 'Lead Auditor'), ('auditor', 'Auditor'), ('reviewer', 'Reviewer')], help_text='Auditor role', max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Auditor organization', max_length=200)),
                ('access_granted_at', models.DateTimeField(blank=True, help_text='When access was granted', null=True)),
                ('last_access_at', models.DateTimeField(blank=True, help_text='Last access timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(help_text='Audit this auditor is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='auditors', to='compliance_audits.complianceaudit')),
                ('user', models.ForeignKey(blank=True, help_text='User if internal auditor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_audit_auditors',
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.CharField(help_text='Finding ID (e.g., F-001)', max_length=100)),
                ('title', models.CharField(help_text='Finding title', max_length=300)),
                ('description', models.TextField(help_text='Finding description')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], help_text='Finding severity', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_remediation', 'In Remediation'), ('resolved', 'Resolved'), ('accepted', 'Accepted')], default='open', help_text='Finding status', max_length=20)),
                ('control_id', models.UUIDField(blank=True, help_text='Related control ID', null=True)),
                ('control_name', models.CharField(blank=True, help_text='Control name', max_length=300)),
                ('framework_id', models.UUIDField(blank=True, help_text='Framework ID', null=True)),
                ('framework_name', models.CharField(blank=True, help_text='Framework name', max_length=200)),
                ('evidence_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Related evidence IDs', size=None)),
                ('remediation_plan', models.TextField(blank=True, help_text='Remediation plan')),
                ('assigned_to', models.CharField(blank=True, help_text='Assigned to (user/team)', max_length=200)),
                ('due_date', models.DateTimeField(blank=True, help_text='Remediation due date', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Resolution date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(help_text='Audit this finding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='compliance_audits.complianceaudit')),
            ],
            options={
                'db_table': 'compliance_audit_findings',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditFrameworkMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework_id', models.UUIDField(help_text='Framework ID (references compliance_frameworks)')),
                ('framework_name', models.CharField(help_text='Framework name for display', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(help_text='Audit being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='compliance_audits.complianceaudit')),
            ],
            options={
                'db_table': 'compliance_audit_framework_mappings',
            },
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['audit_id'], name='compliance__audit_i_465767_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['type', 'status'], name='compliance__type_192fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['start_date', 'end_date'], name='compliance__start_d_85b0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['evidence_locked'], name='compliance__evidenc_f31a89_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['organization_id'], name='compliance__organiz_19f4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditauditor',
            index=models.Index(fields=['audit', 'role'], name='compliance__audit_i_7b9bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditauditor',
            index=models.Index(fields=['user'], name='compliance__user_id_6cc692_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceauditauditor',
            unique_together={('audit', 'email')},
        ),
        migrations.AddIndex(
            model_name='complianceauditfinding',
            index=models.Index(fields=['audit', 'severity'], name='compliance__audit_i_d0d1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditfinding',
            index=models.Index(fields=['audit', 'status'], name='compliance__audit_i_9a60ed_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditfinding',
            index=models.Index(fields=['control_id'], name='compliance__control_3ed5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditframeworkmapping',
            index=models.Index(fields=['framework_id'], name='compliance__framewo_ba1609_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceauditframeworkmapping',
            index=models.Index(fields=['audit', 'framework_id'], name='compliance__audit_i_15d140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceauditframeworkmapping',
            unique_together={('audit', 'framework_id')},
        ),
    ]
