# Generated by Django 5.2.6 on 2025-11-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditreport',
            new_name='audit_repor_user_id_dda0b8_idx',
            old_name='audit_repor_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='auditreport',
            new_name='audit_repor_status_d86143_idx',
            old_name='audit_repor_status_d4e5f6_idx',
        ),
        migrations.AlterModelTable(
            name='auditreport',
            table='audit_reports',
        ),
    ]
