# Generated by Django 5.2.6 on 2025-11-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Domain/URL that was analyzed', max_length=2048)),
                ('a_records', models.JSONField(blank=True, default=list, help_text='List of A records (IPv4 addresses)')),
                ('aaaa_records', models.JSONField(blank=True, default=list, help_text='List of AAAA records (IPv6 addresses)')),
                ('mx_records', models.JSONField(blank=True, default=list, help_text='List of MX records (mail servers)')),
                ('txt_records', models.JSONField(blank=True, default=list, help_text='List of TXT records')),
                ('cname_records', models.JSONField(blank=True, default=list, help_text='List of CNAME records')),
                ('ns_records', models.JSONField(blank=True, default=list, help_text='List of NS records (name servers)')),
                ('soa_record', models.JSONField(blank=True, default=dict, help_text='SOA record information')),
                ('ptr_records', models.JSONField(blank=True, default=list, help_text='List of PTR records')),
                ('srv_records', models.JSONField(blank=True, default=list, help_text='List of SRV records')),
                ('response_time_ms', models.FloatField(blank=True, help_text='DNS query response time in milliseconds', null=True)),
                ('dns_server', models.CharField(blank=True, help_text='DNS server used for query', max_length=255)),
                ('dns_server_ip', models.GenericIPAddressField(blank=True, help_text='IP address of DNS server used', null=True)),
                ('dns_health_score', models.IntegerField(blank=True, help_text='Overall DNS health score (0-100)', null=True)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of DNS issues found')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of DNS recommendations')),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete DNS analysis results')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dns_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DNS Analysis',
                'verbose_name_plural': 'DNS Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='dns_analysi_url_87e863_idx'), models.Index(fields=['user', '-analyzed_at'], name='dns_analysi_user_id_ab315e_idx')],
            },
        ),
    ]
