# Generated by Django 5.2.6 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_analysis', '0002_dnsanalysis_audit_report_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dnsanalysis',
            new_name='dns_analysi_url_9a4bc9_idx',
            old_name='dns_analysi_url_87e863_idx',
        ),
        migrations.RenameIndex(
            model_name='dnsanalysis',
            new_name='dns_analysi_user_id_7bde2d_idx',
            old_name='dns_analysi_user_id_ab315e_idx',
        ),
        migrations.RenameIndex(
            model_name='dnsanalysis',
            new_name='dns_analysi_audit_r_5936a2_idx',
            old_name='dns_analysi_audit_r_1201c5_idx',
        ),
        migrations.AlterModelTable(
            name='dnsanalysis',
            table='dns_analysis',
        ),
    ]
