# Generated by Django 5.2.6 on 2025-12-24 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('database', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Connection',
                'verbose_name_plural': 'Database Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connect', 'Connection'), ('query', 'Query Execution'), ('schema_list', 'Schema List'), ('table_list', 'Table List'), ('column_list', 'Column List'), ('preview', 'Data Preview'), ('error', 'Error')], max_length=50)),
                ('query', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('rows_affected', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='db_management.databaseconnection')),
            ],
            options={
                'verbose_name': 'Database Activity Log',
                'verbose_name_plural': 'Database Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='db_manageme_created_1ee8c6_idx'), models.Index(fields=['connection', '-created_at'], name='db_manageme_connect_2f1193_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatabasePerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_connections', models.IntegerField(default=0)),
                ('active_connections', models.IntegerField(default=0)),
                ('database_size', models.BigIntegerField(blank=True, null=True)),
                ('table_count', models.IntegerField(blank=True, null=True)),
                ('index_count', models.IntegerField(blank=True, null=True)),
                ('cache_hit_ratio', models.FloatField(blank=True, null=True)),
                ('query_performance_avg', models.FloatField(blank=True, null=True)),
                ('slow_queries_count', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='db_management.databaseconnection')),
            ],
            options={
                'verbose_name': 'Database Performance Metric',
                'verbose_name_plural': 'Database Performance Metrics',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['-collected_at'], name='db_manageme_collect_23bb38_idx'), models.Index(fields=['connection', '-collected_at'], name='db_manageme_connect_9ffd28_idx')],
            },
        ),
    ]
