# Generated by Django 5.2.6 on 2025-12-24 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
        ('marketing', '0002_rename_marketing_p_slug_is_a_idx_marketing_p_slug_76c620_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='promotional_deal',
            field=models.ForeignKey(blank=True, help_text='Promotional deal used for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='marketing.promotionaldeal'),
        ),
        migrations.DeleteModel(
            name='PromotionalDeal',
        ),
    ]
