# Generated by Django 5.2.6 on 2025-09-25 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('form_type', models.CharField(choices=[('contact', 'Contact Form'), ('feedback', 'Feedback Form'), ('consultation', 'Consultation Form'), ('update_signup', 'Update Signup')], help_text='Type of form that captured this email', max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Additional form data (name, role, message, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who submitted the form', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this email was captured')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email capture is still active')),
            ],
            options={
                'verbose_name': 'Email Capture',
                'verbose_name_plural': 'Email Captures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='emails_emai_email_ab7db7_idx'), models.Index(fields=['form_type'], name='emails_emai_form_ty_984693_idx'), models.Index(fields=['created_at'], name='emails_emai_created_1a4367_idx')],
            },
        ),
        migrations.CreateModel(
            name='UpdateSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('role', models.CharField(choices=[('Analyst', 'Analyst'), ('Manager', 'Manager'), ('Director', 'Director')], help_text='Role the user is interested in (Analyst, Manager, Director)', max_length=20)),
                ('source', models.CharField(default='upgrade_page', help_text='Where this signup came from', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this signup occurred')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this signup is still active')),
            ],
            options={
                'verbose_name': 'Update Signup',
                'verbose_name_plural': 'Update Signups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='emails_upda_email_6a2f47_idx'), models.Index(fields=['role'], name='emails_upda_role_397443_idx'), models.Index(fields=['created_at'], name='emails_upda_created_312469_idx')],
                'unique_together': {('email', 'role')},
            },
        ),
    ]
