# Generated by Django 5.2.6 on 2025-11-20 08:27

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, help_text="User's email address (optional)", max_length=254, null=True)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('great_work', models.TextField(blank=True, help_text='What did we do great?')),
                ('could_be_better', models.TextField(blank=True, help_text='What could be better?')),
                ('remove_and_relish', models.TextField(blank=True, help_text='What should we remove and relish?')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', help_text='Current status of the feedback', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes about this feedback')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who submitted the feedback', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this feedback was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this feedback was last updated')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this feedback was reviewed', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When a response was sent to the user', null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='emails_feed_status_cdd3eb_idx'), models.Index(fields=['rating'], name='emails_feed_rating_0de44f_idx'), models.Index(fields=['created_at'], name='emails_feed_created_2e94d8_idx'), models.Index(fields=['user_email'], name='emails_feed_user_em_3dcbc3_idx')],
            },
        ),
    ]
