# Generated by Django 5.2.6 on 2025-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcapture',
            name='form_type',
            field=models.CharField(choices=[('contact', 'Contact Form'), ('feedback', 'Feedback Form'), ('consultation', 'Consultation Form'), ('update_signup', 'Update Signup'), ('demo_request', 'Demo Request')], help_text='Type of form that captured this email', max_length=20),
        ),
    ]
