"""
Django management command to seed compliance tools
"""
from django.core.management.base import BaseCommand
from compliance_tools.models import ComplianceTool


class Command(BaseCommand):
    help = 'Seed compliance tools database with initial tool data'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Starting to seed compliance tools...'))
        
        tools_data = [
            # Frameworks
            {
                'name': 'OSCAL (NIST)',
                'tool_type': 'api',
                'sub_category': 'frameworks',
                'status': 'not_configured',
                'description': 'Canonical control schema for SP 800-53 and other frameworks',
                'service': 'NIST OSCAL Content Repository',
                'endpoint': 'https://github.com/usnistgov/oscal-content',
                'repo_url': 'https://github.com/usnistgov/OSCAL',
                'license': 'CC0',
            },
            {
                'name': 'OSCAL Content',
                'tool_type': 'api',
                'sub_category': 'frameworks',
                'status': 'not_configured',
                'description': 'Official NIST control catalogs (SP 800-53 R4, R5) in OSCAL format',
                'service': 'GitHub API / Direct Download',
                'endpoint': 'https://api.github.com/repos/usnistgov/oscal-content',
                'api_key_name': 'GITHUB_TOKEN',
                'repo_url': 'https://github.com/usnistgov/oscal-content',
                'license': 'CC0',
            },
            {
                'name': 'OpenControl',
                'tool_type': 'library',
                'sub_category': 'frameworks',
                'status': 'not_configured',
                'description': 'Control → evidence mapping and compliance-as-code patterns',
                'service': 'Compliance-as-Code Framework',
                'repo_url': 'https://github.com/opencontrol/compliance-masonry',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Compliance Masonry',
                'tool_type': 'library',
                'sub_category': 'frameworks',
                'status': 'not_configured',
                'description': 'Import SOC2 / ISO mappings and control catalogs',
                'service': 'Control Catalog Builder',
                'repo_url': 'https://github.com/opencontrol/compliance-masonry',
                'license': 'Apache 2.0',
            },
            {
                'name': 'OSCAL CLI',
                'tool_type': 'external',
                'sub_category': 'frameworks',
                'status': 'not_configured',
                'description': 'OSCAL catalog validation, conversion, and audit packaging',
                'service': 'Command Line Tool',
                'repo_url': 'https://github.com/usnistgov/oscal-cli',
                'license': 'Apache 2.0',
            },
            # Automated Evidence
            {
                'name': 'SSLyze',
                'tool_type': 'external',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'TLS/SSL certificate and cipher suite analysis',
                'service': 'TLS/SSL Scanner',
                'evidence_produced': 'Certs, ciphers, expiry',
                'repo_url': 'https://github.com/nabla-c0d3/sslyze',
                'license': 'Apache 2.0',
            },
            {
                'name': 'SecurityHeaders',
                'tool_type': 'external',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'HTTP security headers analysis (CSP, HSTS, XFO)',
                'service': 'HTTP Security Headers Scanner',
                'evidence_produced': 'CSP, HSTS, XFO',
                'repo_url': 'https://github.com/securityheaders/securityheaders',
                'license': 'Apache 2.0',
            },
            {
                'name': 'OWASP ZAP',
                'tool_type': 'external',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'Web application vulnerability scanner',
                'service': 'Dynamic Application Security Testing',
                'evidence_produced': 'Vuln scan reports',
                'repo_url': 'https://github.com/zaproxy/zaproxy',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Schemathesis',
                'tool_type': 'library',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'Property-based API testing and compliance validation',
                'service': 'API Testing Framework',
                'evidence_produced': 'API compliance',
                'repo_url': 'https://github.com/schemathesis/schemathesis',
                'license': 'MIT',
            },
            {
                'name': 'Trivy',
                'tool_type': 'external',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'Container vulnerability and misconfiguration scanner',
                'service': 'Container Security Scanner',
                'evidence_produced': 'CVEs, misconfigs',
                'repo_url': 'https://github.com/aquasecurity/trivy',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Gitleaks',
                'tool_type': 'external',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'Detect secrets and credentials in code repositories',
                'service': 'Secrets Detection',
                'evidence_produced': 'Secret detection',
                'repo_url': 'https://github.com/gitleaks/gitleaks',
                'license': 'MIT',
            },
            {
                'name': 'Prowler',
                'tool_type': 'external',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'AWS cloud security assessment and compliance checks',
                'service': 'AWS Security Scanner',
                'evidence_produced': 'IAM & cloud evidence',
                'repo_url': 'https://github.com/prowler-cloud/prowler',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Cloud Custodian',
                'tool_type': 'library',
                'sub_category': 'automated-evidence',
                'status': 'not_configured',
                'description': 'Cloud resource compliance and policy enforcement',
                'service': 'Policy-as-Code Engine',
                'evidence_produced': 'Resource compliance',
                'repo_url': 'https://github.com/cloud-custodian/cloud-custodian',
                'license': 'Apache 2.0',
            },
            # Manual Evidence
            {
                'name': 'Docassemble',
                'tool_type': 'library',
                'sub_category': 'manual-evidence',
                'status': 'not_configured',
                'description': 'Automated evidence collection workflows and questionnaires',
                'service': 'Evidence Intake Workflow',
                'repo_url': 'https://github.com/jhpyle/docassemble',
                'license': 'MIT',
            },
            {
                'name': 'LibreOffice (headless)',
                'tool_type': 'external',
                'sub_category': 'manual-evidence',
                'status': 'not_configured',
                'description': 'Headless document conversion for evidence file processing',
                'service': 'Document Conversion',
                'repo_url': 'https://www.libreoffice.org/download/download/',
                'license': 'MPL',
            },
            {
                'name': 'MinIO',
                'tool_type': 'external',
                'sub_category': 'manual-evidence',
                'status': 'not_configured',
                'description': 'S3-compatible object storage for evidence files (external service)',
                'service': 'Object Storage (S3-compatible)',
                'repo_url': 'https://github.com/minio/minio',
                'license': 'AGPL',
            },
            # Policy Enforcement
            {
                'name': 'Open Policy Agent (OPA)',
                'tool_type': 'library',
                'sub_category': 'policy-enforcement',
                'status': 'not_configured',
                'description': 'Core compliance logic and policy decision engine (MANDATORY)',
                'service': 'Policy Engine',
                'repo_url': 'https://github.com/open-policy-agent/opa',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Rego',
                'tool_type': 'library',
                'sub_category': 'policy-enforcement',
                'status': 'not_configured',
                'description': 'Policy language for control assertions (bundled with OPA)',
                'service': 'Policy Language',
                'repo_url': 'https://github.com/open-policy-agent/opa',
                'license': 'Apache 2.0',
            },
            {
                'name': 'PolicyKit',
                'tool_type': 'library',
                'sub_category': 'policy-enforcement',
                'status': 'not_configured',
                'description': 'RBAC and authorization reference implementation',
                'service': 'Authorization Framework',
                'repo_url': 'https://github.com/polkit-org/polkit',
                'license': 'LGPL',
            },
            # Audit Management
            {
                'name': 'oscal-cli',
                'tool_type': 'external',
                'sub_category': 'audit-management',
                'status': 'not_configured',
                'description': 'OSCAL-based evidence bundles and audit packaging',
                'service': 'Audit Packaging Tool',
                'repo_url': 'https://github.com/usnistgov/oscal-cli',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Auditree',
                'tool_type': 'library',
                'sub_category': 'audit-management',
                'status': 'not_configured',
                'description': 'Automated audit workflow and evidence collection framework (reference)',
                'service': 'Audit Workflow Framework',
                'repo_url': 'https://github.com/auditree/auditree-framework',
                'license': 'GPL',
            },
            # Reporting
            {
                'name': 'WeasyPrint',
                'tool_type': 'library',
                'sub_category': 'reporting',
                'status': 'not_configured',
                'description': 'Generate compliance reports in PDF format from HTML',
                'service': 'HTML to PDF Converter',
                'repo_url': 'https://github.com/Kozea/WeasyPrint',
                'license': 'BSD',
            },
            {
                'name': 'ReportLab',
                'tool_type': 'library',
                'sub_category': 'reporting',
                'status': 'not_configured',
                'description': 'Custom PDF layouts and report generation',
                'service': 'PDF Generation Engine',
                'repo_url': 'https://www.reportlab.com/dev/install/',
                'license': 'BSD',
            },
            {
                'name': 'Jinja2',
                'tool_type': 'library',
                'sub_category': 'reporting',
                'status': 'not_configured',
                'description': 'Report templating and rendering engine',
                'service': 'Template Engine',
                'repo_url': 'https://github.com/pallets/jinja',
                'license': 'BSD',
            },
            {
                'name': 'Pandoc',
                'tool_type': 'external',
                'sub_category': 'reporting',
                'status': 'not_configured',
                'description': 'Universal document converter (optional)',
                'service': 'Document Converter',
                'repo_url': 'https://github.com/jgm/pandoc',
                'license': 'GPL',
            },
            # Continuous Compliance
            {
                'name': 'Prometheus',
                'tool_type': 'external',
                'sub_category': 'continuous-compliance',
                'status': 'not_configured',
                'description': 'Evidence freshness monitoring and metrics collection',
                'service': 'Metrics & Monitoring',
                'evidence_produced': 'Evidence freshness',
                'repo_url': 'https://github.com/prometheus/prometheus',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Falco',
                'tool_type': 'external',
                'sub_category': 'continuous-compliance',
                'status': 'not_configured',
                'description': 'Runtime security monitoring and event detection',
                'service': 'Runtime Security',
                'evidence_produced': 'Runtime events',
                'repo_url': 'https://github.com/falcosecurity/falco',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Elastic ECS',
                'tool_type': 'library',
                'sub_category': 'continuous-compliance',
                'status': 'not_configured',
                'description': 'Event normalization and schema for compliance events',
                'service': 'Event Schema',
                'evidence_produced': 'Normalization',
                'repo_url': 'https://github.com/elastic/ecs',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Celery',
                'tool_type': 'library',
                'sub_category': 'continuous-compliance',
                'status': 'not_configured',
                'description': 'Asynchronous task processing for compliance re-evaluations',
                'service': 'Background Job Engine',
                'evidence_produced': 'Re-evaluations',
                'repo_url': 'https://github.com/celery/celery',
                'license': 'BSD',
            },
            # AI & Privacy
            {
                'name': 'Presidio',
                'tool_type': 'library',
                'sub_category': 'ai-privacy',
                'status': 'not_configured',
                'description': 'Privacy-preserving PII detection for GDPR and AI compliance',
                'service': 'PII Detection',
                'repo_url': 'https://github.com/microsoft/presidio',
                'license': 'Apache 2.0',
            },
            {
                'name': 'OpenLineage',
                'tool_type': 'library',
                'sub_category': 'ai-privacy',
                'status': 'not_configured',
                'description': 'AI traceability and data lineage for compliance',
                'service': 'Data Lineage Tracking',
                'repo_url': 'https://github.com/OpenLineage/OpenLineage',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Marquez',
                'tool_type': 'external',
                'sub_category': 'ai-privacy',
                'status': 'not_configured',
                'description': 'Data lineage backend for OpenLineage (optional)',
                'service': 'Lineage Backend',
                'repo_url': 'https://github.com/MarquezProject/marquez',
                'license': 'Apache 2.0',
            },
            {
                'name': 'Great Expectations',
                'tool_type': 'library',
                'sub_category': 'ai-privacy',
                'status': 'not_configured',
                'description': 'Data quality validation for AI input compliance',
                'service': 'Data Quality Framework',
                'repo_url': 'https://github.com/great-expectations/great_expectations',
                'license': 'Apache 2.0',
            },
        ]
        
        created_count = 0
        updated_count = 0
        
        for tool_data in tools_data:
            tool, created = ComplianceTool.objects.update_or_create(
                name=tool_data['name'],
                defaults=tool_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'  ✓ Created: {tool.name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'  ↻ Updated: {tool.name}'))
        
        self.stdout.write(self.style.SUCCESS(
            f'\nCompleted! Created {created_count} tools, updated {updated_count} tools.'
        ))

