# Generated by Django 5.2.6 on 2025-12-25 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name from lucide-react', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Collateral Category',
                'verbose_name_plural': 'Collateral Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollateralTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this tag represents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collateral Tag',
                'verbose_name_plural': 'Collateral Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterialAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='collateral/avatars/')),
                ('expertise_areas', models.JSONField(blank=True, default=list, help_text='List of expertise areas')),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('author_page_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Material Author',
                'verbose_name_plural': 'Learning Material Authors',
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description/summary', max_length=500)),
                ('content', models.TextField(help_text='Markdown or HTML content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='collateral/images/')),
                ('video_url', models.URLField(blank=True, help_text='URL to video (YouTube, Vimeo, etc.)')),
                ('content_type', models.CharField(choices=[('documentation', 'Documentation'), ('tutorial', 'Tutorial'), ('video', 'Video'), ('guide', 'Guide'), ('quick-start', 'Quick Start'), ('reference', 'Reference'), ('faq', 'FAQ')], default='documentation', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Feature this material prominently')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('read_time', models.IntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='collateral/og_images/')),
                ('language', models.CharField(default='en', max_length=5)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('related_feature', models.CharField(blank=True, help_text="Related feature/page slug (e.g., 'site-audit', 'user-management')", max_length=100)),
                ('related_feature_url', models.CharField(blank=True, help_text="URL to related feature page (e.g., '/workspace/site-audit')", max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collateral.collateralcategory')),
                ('tags', models.ManyToManyField(blank=True, to='collateral.collateraltag')),
            ],
            options={
                'verbose_name': 'Learning Material',
                'verbose_name_plural': 'Learning Materials',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='collateral__status_818900_idx'), models.Index(fields=['featured', '-published_at'], name='collateral__feature_227918_idx'), models.Index(fields=['category', '-published_at'], name='collateral__categor_fe6b62_idx'), models.Index(fields=['content_type', '-published_at'], name='collateral__content_8ee5c0_idx'), models.Index(fields=['related_feature'], name='collateral__related_33fb9e_idx')],
            },
        ),
    ]
