# Generated by Django 5.2.6 on 2025-11-22 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this API', max_length=200)),
                ('url', models.URLField(help_text='Full API endpoint URL', max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('expected_status_code', models.IntegerField(default=200, help_text='Expected HTTP status code')),
                ('timeout_seconds', models.IntegerField(default=10, help_text='Request timeout in seconds')),
                ('check_interval_minutes', models.IntegerField(default=5, help_text='How often to check (minutes)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable monitoring')),
                ('requires_auth', models.BooleanField(default=False, help_text='Requires authentication')),
                ('auth_token', models.CharField(blank=True, help_text='Auth token if needed', max_length=500, null=True)),
                ('headers', models.JSONField(blank=True, help_text='Custom headers as JSON', null=True)),
                ('body', models.TextField(blank=True, help_text='Request body for POST/PUT', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APICheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, help_text='Actual HTTP status code', null=True)),
                ('response_time_ms', models.FloatField(help_text='Response time in milliseconds')),
                ('is_success', models.BooleanField(help_text='Status matches expected?')),
                ('response_body', models.TextField(blank=True, help_text='Response body (truncated if too long)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('endpoint', models.ForeignKey(help_text='API endpoint that was checked', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='api_monitoring.apiendpoint')),
            ],
            options={
                'verbose_name': 'API Check',
                'verbose_name_plural': 'API Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='APIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('down', 'API Down'), ('slow', 'Slow Response'), ('unexpected_status', 'Unexpected Status'), ('timeout', 'Timeout'), ('error', 'Error')], help_text='Type of alert', max_length=50)),
                ('message', models.TextField(help_text='Alert message')),
                ('is_resolved', models.BooleanField(default=False, help_text='Is this alert resolved?')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When was this resolved?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_check', models.ForeignKey(help_text='Check that triggered this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api_monitoring.apicheck')),
                ('endpoint', models.ForeignKey(help_text='API endpoint that triggered alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api_monitoring.apiendpoint')),
            ],
            options={
                'verbose_name': 'API Alert',
                'verbose_name_plural': 'API Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apicheck',
            index=models.Index(fields=['endpoint', '-checked_at'], name='api_monitor_endpoin_d09194_idx'),
        ),
        migrations.AddIndex(
            model_name='apicheck',
            index=models.Index(fields=['is_success', '-checked_at'], name='api_monitor_is_succ_1034da_idx'),
        ),
        migrations.AddIndex(
            model_name='apialert',
            index=models.Index(fields=['is_resolved', '-created_at'], name='api_monitor_is_reso_46ec09_idx'),
        ),
    ]
