# Generated by Django 5.2.6 on 2025-11-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_add_personal_info_and_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('path', models.CharField(help_text='URL path for display', max_length=2048)),
                ('is_internal', models.BooleanField(default=True, help_text='True if link is to same domain')),
                ('is_external', models.BooleanField(default=False)),
                ('is_redirect', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('crawl_session', models.CharField(blank=True, help_text='Crawl session identifier', max_length=255)),
                ('current_status', models.IntegerField(blank=True, help_text='Latest HTTP status code', null=True)),
                ('current_status_text', models.CharField(blank=True, max_length=255)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_links', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('ongoing', 'Ongoing'), ('investigating', 'Investigating')], default='investigating', max_length=20)),
                ('impact', models.CharField(choices=[('full_outage', 'Full Outage'), ('partial_outage', 'Partial Outage'), ('degraded', 'Degraded Performance')], default='degraded', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('root_cause', models.TextField(blank=True, help_text='Root cause description')),
                ('affected_services', models.JSONField(blank=True, default=list, help_text='List of affected services')),
                ('resolution_steps', models.TextField(blank=True, help_text='Steps taken to resolve')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(help_text='HTTP status code')),
                ('status_text', models.CharField(blank=True, max_length=255)),
                ('response_time', models.IntegerField(help_text='Response time in milliseconds')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('redirect_url', models.URLField(blank=True, help_text='Redirect target if status is 3xx', max_length=2048)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.discoveredlink')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSpeedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(help_text='Specific page URL tested', max_length=2048)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=10)),
                ('performance_score', models.IntegerField(help_text='Lighthouse performance score (0-100)')),
                ('lcp', models.FloatField(help_text='Largest Contentful Paint (seconds)')),
                ('fid', models.FloatField(help_text='First Input Delay (milliseconds)')),
                ('cls', models.FloatField(help_text='Cumulative Layout Shift')),
                ('tti', models.FloatField(blank=True, help_text='Time to Interactive (seconds)', null=True)),
                ('tbt', models.FloatField(blank=True, help_text='Total Blocking Time (milliseconds)', null=True)),
                ('fcp', models.FloatField(blank=True, help_text='First Contentful Paint (seconds)', null=True)),
                ('page_size_mb', models.FloatField(blank=True, help_text='Total page size in MB', null=True)),
                ('request_count', models.IntegerField(blank=True, help_text='Number of HTTP requests', null=True)),
                ('load_time', models.FloatField(blank=True, help_text='Total load time in seconds', null=True)),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete Lighthouse results')),
                ('tested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagespeed_results', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseTimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField(blank=True, help_text='Hour of day (0-23) for hourly aggregates', null=True)),
                ('p50', models.FloatField(help_text='50th percentile (median) response time')),
                ('p95', models.FloatField(help_text='95th percentile response time')),
                ('p99', models.FloatField(blank=True, help_text='99th percentile response time', null=True)),
                ('avg', models.FloatField(help_text='Average response time')),
                ('min_response_time', models.IntegerField(help_text='Minimum response time')),
                ('max_response_time', models.IntegerField(help_text='Maximum response time')),
                ('check_count', models.IntegerField(help_text='Number of checks in this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_time_history', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-date', '-hour'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(help_text='Page URL screenshot was taken of', max_length=2048)),
                ('image_url', models.URLField(help_text='URL to stored screenshot image', max_length=2048)),
                ('image_path', models.CharField(blank=True, help_text='File system path if stored locally', max_length=512)),
                ('width', models.IntegerField(help_text='Screenshot width in pixels')),
                ('height', models.IntegerField(help_text='Screenshot height in pixels')),
                ('device_type', models.CharField(blank=True, help_text='Desktop, Mobile, Tablet', max_length=20)),
                ('is_baseline', models.BooleanField(default=False, help_text='True if this is the baseline screenshot')),
                ('diff_percentage', models.FloatField(blank=True, help_text='Percentage difference from baseline', null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('baseline_id', models.ForeignKey(blank=True, help_text='Reference to baseline screenshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons', to='monitoring.screenshot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(help_text='Page URL checked', max_length=2048)),
                ('title_present', models.BooleanField(default=False)),
                ('title_value', models.CharField(blank=True, max_length=255)),
                ('title_length', models.IntegerField(blank=True, null=True)),
                ('meta_description_present', models.BooleanField(default=False)),
                ('meta_description_value', models.TextField(blank=True)),
                ('meta_description_length', models.IntegerField(blank=True, null=True)),
                ('canonical_present', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(blank=True, max_length=2048)),
                ('robots_txt_found', models.BooleanField(default=False)),
                ('robots_txt_content', models.TextField(blank=True)),
                ('og_tags_present', models.BooleanField(default=False)),
                ('og_tags_count', models.IntegerField(default=0)),
                ('og_tags', models.JSONField(blank=True, default=dict, help_text='Open Graph tags as key-value pairs')),
                ('structured_data_present', models.BooleanField(default=False)),
                ('structured_data_type', models.CharField(blank=True, help_text='JSON-LD, Microdata, etc.', max_length=50)),
                ('structured_data_schemas', models.JSONField(blank=True, default=list, help_text='List of schema types found')),
                ('overall_score', models.IntegerField(blank=True, help_text='Overall SEO score (0-100)', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_checks', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField()),
                ('expires_at', models.DateTimeField()),
                ('days_until_expiry', models.IntegerField(help_text='Days until certificate expires')),
                ('issuer', models.CharField(blank=True, help_text="Certificate issuer (e.g., Let's Encrypt)", max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('root_ca_valid', models.BooleanField(default=True)),
                ('intermediate_valid', models.BooleanField(default=True)),
                ('certificate_valid', models.BooleanField(default=True)),
                ('protocol', models.CharField(blank=True, help_text='TLS version (e.g., TLS 1.3)', max_length=20)),
                ('cipher_suite', models.CharField(blank=True, max_length=255)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('checking', 'Checking')], max_length=16)),
                ('response_time', models.IntegerField(help_text='Response time in milliseconds')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if check failed')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional check metadata')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_checks', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.URLField(max_length=2048)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, help_text='JSON, XML, HTML, etc.', max_length=50)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='users.monitoredsite')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['site', '-discovered_at'], name='monitoring__site_id_d8c210_idx')],
                'unique_together': {('site', 'endpoint_url', 'method')},
            },
        ),
        migrations.AddIndex(
            model_name='discoveredlink',
            index=models.Index(fields=['site', '-discovered_at'], name='monitoring__site_id_8f3dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredlink',
            index=models.Index(fields=['is_internal', 'current_status'], name='monitoring__is_inte_02ee4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discoveredlink',
            unique_together={('site', 'url')},
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['site', '-started_at'], name='monitoring__site_id_7a7f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', '-started_at'], name='monitoring__status_78de4e_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcheck',
            index=models.Index(fields=['link', '-checked_at'], name='monitoring__link_id_f55f55_idx'),
        ),
        migrations.AddIndex(
            model_name='linkcheck',
            index=models.Index(fields=['-checked_at'], name='monitoring__checked_dbb0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='pagespeedresult',
            index=models.Index(fields=['site', '-tested_at'], name='monitoring__site_id_ba7cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='pagespeedresult',
            index=models.Index(fields=['page_url', 'device', '-tested_at'], name='monitoring__page_ur_a78a83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagespeedresult',
            unique_together={('site', 'page_url', 'device', 'tested_at')},
        ),
        migrations.AddIndex(
            model_name='responsetimehistory',
            index=models.Index(fields=['site', '-date'], name='monitoring__site_id_aeadc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responsetimehistory',
            unique_together={('site', 'date', 'hour')},
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['site', '-captured_at'], name='monitoring__site_id_41e506_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['page_url', '-captured_at'], name='monitoring__page_ur_55adfb_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['is_baseline'], name='monitoring__is_base_50cc77_idx'),
        ),
        migrations.AddIndex(
            model_name='seocheck',
            index=models.Index(fields=['site', '-checked_at'], name='monitoring__site_id_95ad13_idx'),
        ),
        migrations.AddIndex(
            model_name='seocheck',
            index=models.Index(fields=['page_url', '-checked_at'], name='monitoring__page_ur_902ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['site', '-checked_at'], name='monitoring__site_id_d94ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='statuscheck',
            index=models.Index(fields=['site', '-checked_at'], name='monitoring__site_id_2ac76c_idx'),
        ),
        migrations.AddIndex(
            model_name='statuscheck',
            index=models.Index(fields=['-checked_at'], name='monitoring__checked_4fad7a_idx'),
        ),
    ]
