# Generated by Django 5.2.6 on 2025-11-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_reports', '0002_rename_audit_repor_user_id_a1b2c3_idx_audit_repor_user_id_dda0b8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Base URL that was analyzed', max_length=2048)),
                ('endpoints', models.JSONField(blank=True, default=list, help_text='List of discovered API endpoints with methods, status codes, etc.')),
                ('total_endpoints', models.IntegerField(blank=True, db_index=True, help_text='Total number of endpoints discovered', null=True)),
                ('endpoints_by_method', models.JSONField(blank=True, default=dict, help_text='Count of endpoints by HTTP method')),
                ('endpoints_by_status', models.JSONField(blank=True, default=dict, help_text='Count of endpoints by HTTP status code')),
                ('api_health_score', models.IntegerField(blank=True, help_text='Overall API health score (0-100)', null=True)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of API issues found')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of API recommendations')),
                ('response_types', models.JSONField(blank=True, default=list, help_text='List of response types found (JSON, XML, HTML, etc.)')),
                ('auth_methods', models.JSONField(blank=True, default=list, help_text='Authentication methods detected')),
                ('requires_auth', models.BooleanField(blank=True, help_text='Whether API requires authentication', null=True)),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete API analysis results')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('audit_report', models.ForeignKey(blank=True, help_text='Audit report this analysis belongs to (if part of full audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_analyses', to='audit_reports.auditreport')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Analysis',
                'verbose_name_plural': 'API Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='api_analysi_url_f69b2b_idx'), models.Index(fields=['user', '-analyzed_at'], name='api_analysi_user_id_85acea_idx'), models.Index(fields=['audit_report', '-analyzed_at'], name='api_analysi_audit_r_851984_idx')],
            },
        ),
    ]
