# Generated by Django 5.2.6 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apianalysis',
            new_name='api_analysi_url_e023af_idx',
            old_name='api_analysi_url_f69b2b_idx',
        ),
        migrations.RenameIndex(
            model_name='apianalysis',
            new_name='api_analysi_user_id_30a7df_idx',
            old_name='api_analysi_user_id_85acea_idx',
        ),
        migrations.RenameIndex(
            model_name='apianalysis',
            new_name='api_analysi_audit_r_d1ac78_idx',
            old_name='api_analysi_audit_r_851984_idx',
        ),
        migrations.AlterModelTable(
            name='apianalysis',
            table='api_analysis',
        ),
    ]
