# Generated by Django 5.2.6 on 2025-12-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name (e.g., US East (N. Virginia))', max_length=255)),
                ('region_code', models.CharField(help_text='AWS region code (e.g., us-east-1)', max_length=50, unique=True)),
                ('region_id', models.CharField(help_text='Region identifier', max_length=50)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('continent', models.CharField(help_text='Continent name', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('error', 'Error')], default='pending', help_text='Location status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['continent', 'country', 'name'],
                'indexes': [models.Index(fields=['region_code'], name='multilocati_region__a09777_idx'), models.Index(fields=['status'], name='multilocati_status_5515e4_idx'), models.Index(fields=['continent'], name='multilocati_contine_c81c1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RunnerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_id', models.CharField(help_text='Internal runner identifier (e.g., runner-usw1-001)', max_length=255, unique=True)),
                ('region', models.CharField(help_text='AWS region code (e.g., us-west-1)', max_length=50)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('down', 'Down')], default='down', help_text='Overall health status', max_length=20)),
                ('can_accept_jobs', models.BooleanField(default=False, help_text='Can this runner run Lighthouse now?')),
                ('cpu_load', models.FloatField(blank=True, help_text='CPU load average', null=True)),
                ('memory_used_mb', models.IntegerField(blank=True, help_text='Memory used in MB', null=True)),
                ('memory_total_mb', models.IntegerField(blank=True, help_text='Total memory in MB', null=True)),
                ('disk_free_mb', models.IntegerField(blank=True, help_text='Available disk space in MB', null=True)),
                ('latency_ms', models.IntegerField(blank=True, help_text='Response time to orchestrator in milliseconds', null=True)),
                ('current_jobs_running', models.IntegerField(default=0, help_text='Number of current jobs running')),
                ('last_lighthouse_run_sec', models.IntegerField(blank=True, help_text='Seconds since last successful Lighthouse job', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last health check timestamp')),
                ('location', models.ForeignKey(help_text='Associated location', on_delete=django.db.models.deletion.CASCADE, related_name='runner_health', to='multilocation.location')),
            ],
            options={
                'verbose_name': 'Runner Health',
                'verbose_name_plural': 'Runner Health Records',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['runner_id'], name='multilocati_runner__d8244a_idx'), models.Index(fields=['status'], name='multilocati_status_d153bc_idx'), models.Index(fields=['can_accept_jobs'], name='multilocati_can_acc_31f19a_idx'), models.Index(fields=['location', 'status'], name='multilocati_locatio_77eb09_idx'), models.Index(fields=['updated_at'], name='multilocati_updated_bb6bf6_idx')],
            },
        ),
    ]
