# Generated by Django 5.2.6 on 2025-11-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_reports', '0002_rename_audit_repor_user_id_a1b2c3_idx_audit_repor_user_id_dda0b8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='URL that was analyzed', max_length=2048)),
                ('is_valid', models.BooleanField(help_text='Whether SSL certificate is valid')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Certificate expiration date/time', null=True)),
                ('days_until_expiry', models.IntegerField(blank=True, help_text='Days until certificate expires', null=True)),
                ('issuer', models.CharField(blank=True, help_text="Certificate issuer (e.g., Let's Encrypt)", max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Certificate subject', max_length=255)),
                ('serial_number', models.CharField(blank=True, help_text='Certificate serial number', max_length=255)),
                ('root_ca_valid', models.BooleanField(default=True, help_text='Root CA certificate is valid')),
                ('intermediate_valid', models.BooleanField(default=True, help_text='Intermediate certificate is valid')),
                ('certificate_valid', models.BooleanField(default=True, help_text='Certificate itself is valid')),
                ('protocol', models.CharField(blank=True, help_text='TLS version (e.g., TLS 1.3)', max_length=20)),
                ('cipher_suite', models.CharField(blank=True, help_text='Cipher suite used', max_length=255)),
                ('certificate_chain', models.JSONField(blank=True, default=list, help_text='Full certificate chain information')),
                ('san_domains', models.JSONField(blank=True, default=list, help_text='Subject Alternative Names (SAN) domains')),
                ('ssl_health_score', models.IntegerField(blank=True, help_text='Overall SSL health score (0-100)', null=True)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of SSL issues found')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of SSL recommendations')),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete SSL analysis results')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('audit_report', models.ForeignKey(blank=True, help_text='Audit report this analysis belongs to (if part of full audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_analyses', to='audit_reports.auditreport')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssl_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSL Analysis',
                'verbose_name_plural': 'SSL Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='ssl_analysi_url_163651_idx'), models.Index(fields=['user', '-analyzed_at'], name='ssl_analysi_user_id_8fd85e_idx'), models.Index(fields=['audit_report', '-analyzed_at'], name='ssl_analysi_audit_r_27c47b_idx'), models.Index(fields=['is_valid'], name='ssl_analysi_is_vali_335787_idx')],
            },
        ),
    ]
