# Generated by Django 5.2.6 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sslanalysis',
            new_name='ssl_analysi_url_36d768_idx',
            old_name='ssl_analysi_url_163651_idx',
        ),
        migrations.RenameIndex(
            model_name='sslanalysis',
            new_name='ssl_analysi_user_id_2ebd14_idx',
            old_name='ssl_analysi_user_id_8fd85e_idx',
        ),
        migrations.RenameIndex(
            model_name='sslanalysis',
            new_name='ssl_analysi_audit_r_53d134_idx',
            old_name='ssl_analysi_audit_r_27c47b_idx',
        ),
        migrations.RenameIndex(
            model_name='sslanalysis',
            new_name='ssl_analysi_is_vali_d45a5c_idx',
            old_name='ssl_analysi_is_vali_335787_idx',
        ),
        migrations.AlterModelTable(
            name='sslanalysis',
            table='ssl_analysis',
        ),
    ]
