# Generated by Django 5.2.6 on 2026-01-04 21:30

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_id', models.CharField(help_text='Control ID (e.g., SOC2-CC6.1)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Control name', max_length=300)),
                ('description', models.TextField(help_text='Control description')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial'), ('not_evaluated', 'Not Evaluated')], default='not_evaluated', help_text='Control status', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Control severity', max_length=20)),
                ('last_evaluated', models.DateTimeField(blank=True, help_text='Last evaluation date', null=True)),
                ('evaluation_method', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual'), ('hybrid', 'Hybrid')], default='automated', help_text='Evaluation method', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure if status is fail')),
                ('failing_assets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='List of failing asset IDs or names', size=None)),
                ('failing_count', models.IntegerField(default=0, help_text='Number of assets failing this control')),
                ('uptime_percentage', models.FloatField(blank=True, help_text='Control uptime percentage over time period', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_out_of_compliance', models.IntegerField(blank=True, help_text='Time out of compliance in minutes', null=True)),
                ('fix_recommendations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='List of fix recommendations', size=None)),
                ('related_control_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='Related control IDs', size=None)),
                ('category', models.CharField(blank=True, help_text='Control category', max_length=100)),
                ('control_type', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective')], default='preventive', help_text='Type of control', max_length=20)),
                ('frequency', models.CharField(choices=[('continuous', 'Continuous'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='continuous', help_text='Evaluation frequency', max_length=20)),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization/tenant ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controls', to=settings.AUTH_USER_MODEL)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Control',
                'verbose_name_plural': 'Compliance Controls',
                'db_table': 'compliance_controls',
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControlFrameworkMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework_id', models.UUIDField(help_text='Framework ID (references compliance_frameworks)')),
                ('framework_name', models.CharField(help_text='Framework name for display', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(help_text='Control being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='compliance_controls.compliancecontrol')),
            ],
            options={
                'db_table': 'compliance_control_framework_mappings',
            },
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['control_id'], name='compliance__control_9956b4_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['status', 'severity'], name='compliance__status_0ffaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['evaluation_method'], name='compliance__evaluat_9882f2_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['organization_id'], name='compliance__organiz_133008_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrolframeworkmapping',
            index=models.Index(fields=['framework_id'], name='compliance__framewo_aab01e_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrolframeworkmapping',
            index=models.Index(fields=['control', 'framework_id'], name='compliance__control_02b081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecontrolframeworkmapping',
            unique_together={('control', 'framework_id')},
        ),
    ]
