# Generated by Django 5.2.6 on 2026-01-07 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEvidenceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('tls_scan', 'TLS Scan'), ('dast', 'DAST'), ('security_scan', 'Security Scan'), ('config_scan', 'Config Scan'), ('ai_monitor', 'AI Monitor'), ('system_log', 'System Log'), ('manual_upload', 'Manual Upload'), ('policy_document', 'Policy Document'), ('attestation', 'Attestation')], help_text='Type of evidence required', max_length=50)),
                ('source_app', models.CharField(blank=True, help_text='Source application/tool that produces this evidence (e.g., SSLyze, Nuclei)', max_length=100)),
                ('freshness_days', models.IntegerField(default=30, help_text='Maximum age of evidence in days before it expires')),
                ('required', models.BooleanField(default=True, help_text='Whether this evidence is required (True) or optional (False)')),
                ('description', models.TextField(blank=True, help_text='Description of what evidence is expected')),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization/tenant ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(help_text='Control that requires this evidence', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='compliance_controls.compliancecontrol')),
            ],
            options={
                'verbose_name': 'Control Evidence Requirement',
                'verbose_name_plural': 'Control Evidence Requirements',
                'db_table': 'compliance_control_evidence_requirements',
                'indexes': [models.Index(fields=['control'], name='compliance__control_c24645_idx'), models.Index(fields=['evidence_type'], name='compliance__evidenc_2f6cb1_idx'), models.Index(fields=['organization_id'], name='compliance__organiz_e53a5e_idx')],
                'unique_together': {('control', 'evidence_type', 'source_app')},
            },
        ),
    ]
