# Generated by Django 5.2.6 on 2026-01-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_controls', '0002_controlevidencerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlevidencerequirement',
            name='collection_method',
            field=models.CharField(blank=True, choices=[('automated_scan', 'Automated Scan'), ('automated_log', 'Automated Log'), ('automated_config', 'Automated Config'), ('manual_upload', 'Manual Upload'), ('manual_attestation', 'Manual Attestation'), ('manual_screenshot', 'Manual Screenshot')], help_text='How evidence is collected (automated vs manual)', max_length=30),
        ),
        migrations.AddField(
            model_name='controlevidencerequirement',
            name='evidence_category',
            field=models.CharField(blank=True, choices=[('security_scan', 'Security Scan'), ('tls_config', 'TLS Configuration'), ('cloud_config', 'Cloud Configuration'), ('access_log', 'Access Log'), ('system_log', 'System Log'), ('policy_document', 'Policy Document'), ('attestation', 'Attestation'), ('screenshot', 'Screenshot')], help_text='Category of evidence (security_scan, tls_config, etc.)', max_length=30),
        ),
        migrations.AlterField(
            model_name='controlevidencerequirement',
            name='evidence_type',
            field=models.CharField(choices=[('tls_scan', 'TLS Scan'), ('dast', 'DAST'), ('security_scan', 'Security Scan'), ('config_scan', 'Config Scan'), ('ai_monitor', 'AI Monitor'), ('system_log', 'System Log'), ('manual_upload', 'Manual Upload'), ('policy_document', 'Policy Document'), ('attestation', 'Attestation')], help_text='Type of evidence required (legacy field)', max_length=50),
        ),
    ]
