# Generated by Django 5.2.6 on 2026-01-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_controls', '0003_add_evidence_category_collection_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlevidencerequirement',
            name='evidence_category',
            field=models.CharField(blank=True, choices=[('security_scan', 'Security Scan'), ('tls_config', 'TLS Configuration'), ('cloud_config', 'Cloud Configuration'), ('access_log', 'Access Log'), ('system_log', 'System Log'), ('attestation', 'Attestation'), ('screenshot', 'Screenshot'), ('document', 'Document Upload')], help_text='Category of evidence (security_scan, tls_config, etc.)', max_length=30),
        ),
    ]
