# Generated by Django 5.2.6 on 2025-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_monitoring', '0004_securitytool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitytool',
            name='category',
            field=models.CharField(choices=[('site_audit', 'Site Audit'), ('security', 'Security'), ('api', 'API'), ('performance', 'Performance')], default='security', help_text='Tool category for organization', max_length=20),
        ),
    ]
