# Generated by Django 5.2.6 on 2026-01-04 21:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_id', models.CharField(help_text='Evidence ID (e.g., EV-001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Evidence name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Evidence description')),
                ('source', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual')], help_text='Evidence source type', max_length=20)),
                ('source_type', models.CharField(choices=[('ai_monitor', 'AI Monitor'), ('dast', 'DAST'), ('security_scan', 'Security Scan'), ('tls_scan', 'TLS Scan'), ('config_scan', 'Config Scan'), ('manual_upload', 'Manual Upload'), ('system_log', 'System Log')], help_text='Specific source type', max_length=30)),
                ('source_name', models.CharField(help_text='Source name (e.g., AI Monitor, Attack Surface Scan)', max_length=200)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon')], default='fresh', help_text='Evidence status', max_length=20)),
                ('validity_period', models.IntegerField(blank=True, help_text='Validity period in days', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, help_text='File type (pdf, png, json, etc.)', max_length=50)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_url', models.URLField(blank=True, help_text='URL to evidence file', max_length=500)),
                ('preview_url', models.URLField(blank=True, help_text='URL to preview/thumbnail', max_length=500)),
                ('content', models.TextField(blank=True, help_text='Evidence content (for text-based evidence)')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Evidence tags', size=None)),
                ('category', models.CharField(blank=True, help_text='Evidence category', max_length=100)),
                ('audit_locked', models.BooleanField(default=False, help_text='Whether evidence is locked for an audit')),
                ('audit_id', models.UUIDField(blank=True, help_text='Audit ID if locked', null=True)),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization/tenant ID', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded (for manual evidence)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Evidence',
                'verbose_name_plural': 'Compliance Evidence',
                'db_table': 'compliance_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidenceControlMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_id', models.UUIDField(help_text='Control ID (references compliance_controls)')),
                ('control_name', models.CharField(help_text='Control name for display', max_length=300)),
                ('framework_id', models.UUIDField(help_text='Framework ID')),
                ('framework_name', models.CharField(help_text='Framework name for display', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(help_text='Evidence being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='control_mappings', to='compliance_evidence.complianceevidence')),
            ],
            options={
                'db_table': 'compliance_evidence_control_mappings',
            },
        ),
        migrations.AddIndex(
            model_name='complianceevidence',
            index=models.Index(fields=['evidence_id'], name='compliance__evidenc_63a5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidence',
            index=models.Index(fields=['source', 'source_type'], name='compliance__source_fa5877_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidence',
            index=models.Index(fields=['status', 'expires_at'], name='compliance__status_812e47_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidence',
            index=models.Index(fields=['audit_locked', 'audit_id'], name='compliance__audit_l_384618_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidence',
            index=models.Index(fields=['organization_id'], name='compliance__organiz_a63df5_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidencecontrolmapping',
            index=models.Index(fields=['control_id'], name='compliance__control_b9a12a_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidencecontrolmapping',
            index=models.Index(fields=['framework_id'], name='compliance__framewo_a0de5a_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidencecontrolmapping',
            index=models.Index(fields=['evidence', 'control_id'], name='compliance__evidenc_6f2368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceevidencecontrolmapping',
            unique_together={('evidence', 'control_id')},
        ),
    ]
