# Generated by Django 5.2.6 on 2026-01-04 21:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(help_text='Report ID (e.g., RPT-001, SOC2-READINESS-2024-Q1)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Report name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Report description')),
                ('type', models.CharField(choices=[('readiness', 'Readiness'), ('gap_analysis', 'Gap Analysis'), ('continuous_monitoring', 'Continuous Monitoring'), ('executive_summary', 'Executive Summary'), ('technical_report', 'Technical Report'), ('auditor_report', 'Auditor Report')], help_text='Report type', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Report status', max_length=20)),
                ('view', models.CharField(choices=[('executive', 'Executive'), ('technical', 'Technical'), ('auditor', 'Auditor')], help_text='Report view type', max_length=20)),
                ('date_range_start', models.DateTimeField(blank=True, help_text='Report date range start', null=True)),
                ('date_range_end', models.DateTimeField(blank=True, help_text='Report date range end', null=True)),
                ('includes_evidence', models.BooleanField(default=False, help_text='Whether report includes evidence')),
                ('evidence_count', models.IntegerField(blank=True, help_text='Number of evidence items included', null=True)),
                ('includes_controls', models.BooleanField(default=False, help_text='Whether report includes controls')),
                ('control_count', models.IntegerField(blank=True, help_text='Number of controls included', null=True)),
                ('includes_policies', models.BooleanField(default=False, help_text='Whether report includes policies')),
                ('policy_count', models.IntegerField(blank=True, help_text='Number of policies included', null=True)),
                ('template_id', models.CharField(blank=True, help_text='Template ID used', max_length=100)),
                ('template_name', models.CharField(blank=True, help_text='Template name', max_length=200)),
                ('generated_at', models.DateTimeField(blank=True, help_text='Generation date', null=True)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML'), ('zip', 'ZIP'), ('readonly_link', 'Read-only Link')], default='pdf', help_text='Report file format', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_url', models.URLField(blank=True, help_text='URL to report file', max_length=500)),
                ('download_url', models.URLField(blank=True, help_text='Download URL', max_length=500)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Report summary statistics')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization/tenant ID', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'db_table': 'compliance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReportFrameworkMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework_id', models.UUIDField(help_text='Framework ID (references compliance_frameworks)')),
                ('framework_name', models.CharField(help_text='Framework name for display', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(help_text='Report being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='framework_mappings', to='compliance_reports.compliancereport')),
            ],
            options={
                'db_table': 'compliance_report_framework_mappings',
            },
        ),
        migrations.CreateModel(
            name='ComplianceReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(help_text='Share link URL', max_length=500, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Link expiration date', null=True)),
                ('password_protected', models.BooleanField(default=False, help_text='Whether link is password protected')),
                ('password_hash', models.CharField(blank=True, help_text='Hashed password if protected', max_length=255)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times link was accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_shares', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Report being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='compliance_reports.compliancereport')),
            ],
            options={
                'db_table': 'compliance_report_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['report_id'], name='compliance__report__cfd2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['type', 'status'], name='compliance__type_eb1719_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['status'], name='compliance__status_dd1ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['generated_at'], name='compliance__generat_e629d2_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['organization_id'], name='compliance__organiz_cb1181_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportframeworkmapping',
            index=models.Index(fields=['framework_id'], name='compliance__framewo_6b9b83_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportframeworkmapping',
            index=models.Index(fields=['report', 'framework_id'], name='compliance__report__cf8420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancereportframeworkmapping',
            unique_together={('report', 'framework_id')},
        ),
        migrations.AddIndex(
            model_name='compliancereportshare',
            index=models.Index(fields=['report'], name='compliance__report__e1ce4a_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportshare',
            index=models.Index(fields=['link'], name='compliance__link_5fd9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportshare',
            index=models.Index(fields=['expires_at'], name='compliance__expires_f71172_idx'),
        ),
    ]
