# Generated by Django 5.2.2 on 2025-09-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_role'),
    ]

    operations = [
    ]
