# Generated by Django 5.2.2 on 2025-09-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_auto_20250926_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
