# Generated by Django 5.2.6 on 2025-10-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_custom_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
