# Generated by Django 5.2.6 on 2025-11-07 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_billingtransaction_paymentmethod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('checking', 'Checking'), ('up', 'Up'), ('down', 'Down')], default='checking', max_length=16)),
                ('uptime', models.FloatField(default=100.0)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.IntegerField(default=0)),
                ('status_duration', models.CharField(blank=True, max_length=255)),
                ('check_interval', models.IntegerField(default=5)),
                ('ssl_valid', models.BooleanField(blank=True, null=True)),
                ('ssl_expires_in', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'url')},
            },
        ),
    ]
