# Generated by Django 5.2.6 on 2025-11-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Encrypted backup codes for 2FA recovery'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether the user has enabled 2FA'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='Encrypted TOTP secret for 2FA', max_length=255, null=True),
        ),
    ]
