# Generated by Django 5.2.6 on 2025-11-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_two_factor_backup_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='Plain text verification code for fallback retrieval', max_length=255, null=True),
        ),
    ]
