# Generated by Django 5.2.6 on 2025-11-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL to user avatar image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography or description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locale',
            field=models.CharField(default='en-US', help_text='User locale preference', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Personal phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User timezone', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_settings',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences and settings'),
        ),
    ]
