# Generated by Django 5.2.6 on 2025-11-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_email_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='routing_last4',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, help_text='Full account number (encrypted in production)', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, help_text='Full 16-digit card number (encrypted in production)', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(blank=True, help_text='Cardholder name for credit/debit cards', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='routing_number',
            field=models.CharField(blank=True, help_text='Full 9-digit routing number', max_length=9),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text='Monthly or Annual billing', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='discount_code',
            field=models.CharField(blank=True, help_text='Promotional discount code applied to this subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price in USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='brand',
            field=models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='last4',
            field=models.CharField(blank=True, help_text='Last 4 digits for display purposes', max_length=4),
        ),
    ]
