# Generated by Django 5.2.6 on 2025-12-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0012_add_personal_info_and_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Permission code (e.g., "site_audit.view")', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name (e.g., "View Site Audits")', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('category', models.CharField(choices=[('workspace', 'Workspace'), ('user_features', 'User Features'), ('admin_features', 'Admin Features'), ('account', 'Account')], help_text='Category this permission belongs to', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_permission', models.ForeignKey(blank=True, help_text='Linked Django permission (optional, for integration)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Feature Permission',
                'verbose_name_plural': 'Feature Permissions',
                'ordering': ['category', 'code'],
            },
        ),
    ]
