# Generated by Django 5.2.6 on 2025-12-08 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_featurepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Billing contact first name', max_length=100)),
                ('last_name', models.CharField(help_text='Billing contact last name', max_length=100)),
                ('email', models.EmailField(help_text='Billing contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Billing contact phone number', max_length=50)),
                ('company_name', models.CharField(blank=True, help_text='Company name (if business billing)', max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID / VAT number (if applicable)', max_length=100)),
                ('address_line1', models.CharField(help_text='Street address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Street address line 2 (apartment, suite, etc.)', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State / Province / Region', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal / ZIP code', max_length=20)),
                ('country', models.CharField(help_text='Country (ISO country code recommended)', max_length=100)),
                ('payment_provider', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('coinbase', 'Coinbase')], default='paypal', help_text='Payment provider this address came from', max_length=50)),
                ('provider_address_id', models.CharField(blank=True, help_text='Address ID from payment provider (if available)', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default billing address for the user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this address is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this address was used for a transaction', null=True)),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
                'ordering': ['-is_default', '-last_used_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('coinbase', 'Coinbase')], help_text='Payment provider name', max_length=50, unique=True)),
                ('client_id', models.CharField(blank=True, help_text='Client ID / Public Key', max_length=255)),
                ('client_secret', models.CharField(blank=True, help_text='Client Secret / Private Key (encrypted)', max_length=255)),
                ('webhook_id', models.CharField(blank=True, help_text='Webhook ID from provider', max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL configured in provider dashboard')),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook secret for signature verification', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this provider is active and enabled')),
                ('is_live', models.BooleanField(default=False, help_text='True for live/production, False for sandbox/test')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time data was synced from provider', null=True)),
            ],
            options={
                'verbose_name': 'Payment Provider Config',
                'verbose_name_plural': 'Payment Provider Configs',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='Internal plan name (Analyst, Auditor, Manager, etc.)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Plan description')),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, help_text='Yearly price in USD (with discount applied)', max_digits=10)),
                ('paypal_plan_id_monthly', models.CharField(blank=True, help_text='PayPal billing plan ID for monthly billing (P-XXXXX)', max_length=255)),
                ('paypal_plan_id_annual', models.CharField(blank=True, help_text='PayPal billing plan ID for annual billing (P-XXXXX)', max_length=255)),
                ('paypal_product_id', models.CharField(blank=True, help_text='PayPal product ID (PROD-XXXXX)', max_length=255)),
                ('stripe_plan_id_monthly', models.CharField(blank=True, help_text='Stripe plan ID for monthly billing', max_length=255)),
                ('stripe_plan_id_annual', models.CharField(blank=True, help_text='Stripe plan ID for annual billing', max_length=255)),
                ('coinbase_plan_id_monthly', models.CharField(blank=True, help_text='Coinbase plan ID for monthly billing', max_length=255)),
                ('coinbase_plan_id_annual', models.CharField(blank=True, help_text='Coinbase plan ID for annual billing', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to highlight this plan (e.g., "Most Popular")')),
                ('role', models.CharField(blank=True, help_text='Associated user role (viewer, analyst, manager, etc.)', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display plans (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='payment_provider',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('coinbase', 'Coinbase')], default='paypal', help_text='Payment provider used', max_length=50),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='paypal_payment_id',
            field=models.CharField(blank=True, help_text='PayPal payment ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='paypal_sale_id',
            field=models.CharField(blank=True, help_text='PayPal sale ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, help_text='PayPal transaction ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the transaction was processed by the payment provider', null=True),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Associated subscription if this is a recurring payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.usersubscription'),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('subscription', 'Subscription Payment'), ('one_time', 'One-time Payment'), ('refund', 'Refund'), ('chargeback', 'Chargeback')], default='subscription', help_text='Type of transaction', max_length=50),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, help_text='Next billing date from PayPal', null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_plan_id',
            field=models.CharField(blank=True, help_text='PayPal billing plan ID (P-XXXXX)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_product_id',
            field=models.CharField(blank=True, help_text='PayPal product ID (PROD-XXXXX)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_status',
            field=models.CharField(blank=True, help_text='PayPal subscription status (ACTIVE, CANCELLED, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, help_text='PayPal subscription ID (I-XXXXX)', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='billingtransaction',
            index=models.Index(fields=['paypal_transaction_id'], name='users_billi_paypal__7f733b_idx'),
        ),
        migrations.AddIndex(
            model_name='billingtransaction',
            index=models.Index(fields=['user', 'status'], name='users_billi_user_id_fb5aff_idx'),
        ),
        migrations.AddIndex(
            model_name='billingtransaction',
            index=models.Index(fields=['subscription'], name='users_billi_subscri_20b902_idx'),
        ),
        migrations.AddIndex(
            model_name='billingtransaction',
            index=models.Index(fields=['payment_provider'], name='users_billi_payment_87f58b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['paypal_subscription_id'], name='users_users_paypal__8cc08e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='users_users_user_id_4cec3f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['paypal_status'], name='users_users_paypal__4270bd_idx'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Associated subscription if this is the subscription billing address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_addresses', to='users.usersubscription'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(help_text='User who owns this billing address', on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentproviderconfig',
            index=models.Index(fields=['provider'], name='users_payme_provide_128315_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['plan_name'], name='users_subsc_plan_na_090e32_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active'], name='users_subsc_is_acti_06bd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['user', 'is_default'], name='users_billi_user_id_83cbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['subscription'], name='users_billi_subscri_cb3bec_idx'),
        ),
        migrations.AddIndex(
            model_name='billingaddress',
            index=models.Index(fields=['payment_provider'], name='users_billi_payment_a3a8ab_idx'),
        ),
    ]
