# Generated by Django 5.2.6 on 2025-12-08 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_billingaddress_paymentproviderconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='deal_redeemed_at',
            field=models.DateTimeField(blank=True, help_text='When the promotional deal was redeemed', null=True),
        ),
        migrations.CreateModel(
            name='PromotionalDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Deal name (e.g., "Black Friday 2025")', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Deal description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 44.00 for 44% off)', max_digits=5)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price before discount', max_digits=10)),
                ('deal_price', models.DecimalField(decimal_places=2, help_text='Deal price (e.g., 199.00 for $199/year)', max_digits=10)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Billing period for this deal', max_length=20)),
                ('paypal_plan_id', models.CharField(blank=True, help_text='PayPal billing plan ID for this deal (P-XXXXX)', max_length=200, null=True)),
                ('paypal_product_id', models.CharField(blank=True, help_text='PayPal product ID (PROD-XXXXX)', max_length=200, null=True)),
                ('start_date', models.DateTimeField(help_text='When the deal becomes active')),
                ('end_date', models.DateTimeField(help_text='When the deal expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this deal is currently active')),
                ('max_redemptions', models.IntegerField(blank=True, help_text='Maximum number of redemptions (null = unlimited)', null=True)),
                ('current_redemptions', models.IntegerField(default=0, help_text='Current number of redemptions')),
                ('badge_text', models.CharField(default='LIMITED TIME DEAL', help_text='Badge text to display (e.g., "LIMITED TIME DEAL")', max_length=50)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage banner')),
                ('display_priority', models.IntegerField(default=0, help_text='Display priority (higher = shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_plan', models.ForeignKey(help_text='Base subscription plan this deal applies to', on_delete=django.db.models.deletion.CASCADE, related_name='promotional_deals', to='users.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Promotional Deal',
                'verbose_name_plural': 'Promotional Deals',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='promotional_deal',
            field=models.ForeignKey(blank=True, help_text='Promotional deal used for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='users.promotionaldeal'),
        ),
        migrations.AddIndex(
            model_name='promotionaldeal',
            index=models.Index(fields=['slug', 'is_active'], name='users_promo_slug_5f6340_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionaldeal',
            index=models.Index(fields=['start_date', 'end_date'], name='users_promo_start_d_1c958e_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionaldeal',
            index=models.Index(fields=['featured', 'is_active'], name='users_promo_feature_f33f10_idx'),
        ),
    ]
