# Generated by Django 5.2.6 on 2025-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usersubscription_deal_redeemed_at_promotionaldeal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionaldeal',
            name='coinbase_plan_id',
            field=models.CharField(blank=True, help_text='Coinbase plan ID for this deal', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldeal',
            name='stripe_plan_id',
            field=models.CharField(blank=True, help_text='Stripe price/plan ID for this deal', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promotionaldeal',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe product ID', max_length=200, null=True),
        ),
    ]
