# Generated by Django 5.2.6 on 2025-12-09 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_stripe_coinbase_to_deals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(help_text='Coinbase Commerce charge ID', max_length=255, unique=True)),
                ('charge_code', models.CharField(blank=True, help_text='Charge code for payment URL matching', max_length=255, null=True, unique=True)),
                ('hosted_url', models.URLField(blank=True, help_text='Coinbase checkout URL')),
                ('name', models.CharField(help_text='Charge name/description', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Original USD amount requested', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Base currency (usually USD)', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('delayed', 'Delayed')], default='pending', help_text='Charge status from Coinbase', max_length=20)),
                ('pricing_type', models.CharField(default='fixed_price', help_text='Pricing type: fixed_price or no_price', max_length=20)),
                ('redirect_url', models.URLField(blank=True, help_text='Where to redirect after successful payment')),
                ('cancel_url', models.URLField(blank=True, help_text='Where to redirect if payment is canceled')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from charge creation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the charge expires if not paid', null=True)),
            ],
            options={
                'verbose_name': 'Coinbase Charge',
                'verbose_name_plural': 'Coinbase Charges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinbaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Coinbase transaction ID', max_length=255, unique=True)),
                ('crypto_currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDC', 'USD Coin'), ('LTC', 'Litecoin'), ('DOGE', 'Dogecoin'), ('BCH', 'Bitcoin Cash')], help_text='Cryptocurrency used for payment', max_length=10)),
                ('crypto_amount', models.DecimalField(decimal_places=8, help_text='Amount received in cryptocurrency', max_digits=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='USD equivalent at time of payment', max_digits=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion', max_digits=20, null=True)),
                ('network', models.CharField(blank=True, help_text='Blockchain network (mainnet, testnet)', max_length=50, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255, null=True)),
                ('block_height', models.IntegerField(blank=True, help_text='Block height when confirmed', null=True)),
                ('confirmations', models.IntegerField(default=0, help_text='Number of blockchain confirmations')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('delayed', 'Delayed')], default='pending', help_text='Transaction status', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Wallet type or payment method used', max_length=100, null=True)),
                ('timeline', models.JSONField(blank=True, default=list, help_text='Full payment timeline from Coinbase API')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When payment was confirmed and processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coinbase Transaction',
                'verbose_name_plural': 'Coinbase Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='coinbase_charge_id',
            field=models.CharField(blank=True, help_text='Coinbase Commerce charge ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='coinbase_code',
            field=models.CharField(blank=True, help_text='Coinbase charge code (for payment URL)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agency', 'Agency'), ('executive', 'Executive'), ('director', 'Director'), ('manager', 'Manager'), ('analyst', 'Analyst'), ('auditor', 'Auditor'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='billingtransaction',
            index=models.Index(fields=['coinbase_charge_id'], name='users_billi_coinbas_975f6a_idx'),
        ),
        migrations.AddField(
            model_name='coinbasecharge',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coinbase_charges', to='users.usersubscription'),
        ),
        migrations.AddField(
            model_name='coinbasecharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coinbasetransaction',
            name='charge',
            field=models.ForeignKey(help_text='Associated charge', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.coinbasecharge'),
        ),
        migrations.AddField(
            model_name='coinbasetransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coinbase_transactions', to='users.usersubscription'),
        ),
        migrations.AddField(
            model_name='coinbasetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coinbasecharge',
            index=models.Index(fields=['charge_id'], name='users_coinb_charge__72f19c_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasecharge',
            index=models.Index(fields=['charge_code'], name='users_coinb_charge__9f97a9_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasecharge',
            index=models.Index(fields=['user', 'status'], name='users_coinb_user_id_34d608_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasecharge',
            index=models.Index(fields=['created_at'], name='users_coinb_created_043f88_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['transaction_id'], name='users_coinb_transac_2bcb46_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['charge', 'status'], name='users_coinb_charge__a7f366_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['user', 'status'], name='users_coinb_user_id_29c794_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['crypto_currency'], name='users_coinb_crypto__a65fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['created_at'], name='users_coinb_created_a517f7_idx'),
        ),
    ]
