# Generated by Django 5.2.6 on 2025-12-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_create_coinbase_tables'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingtransaction',
            name='users_billi_coinbas_975f6a_idx',
        ),
        migrations.RemoveField(
            model_name='billingtransaction',
            name='coinbase_charge_id',
        ),
        migrations.RemoveField(
            model_name='billingtransaction',
            name='coinbase_code',
        ),
    ]
