# Generated by Django 5.2.6 on 2025-12-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_coinbase_from_billing_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name (e.g., US East (N. Virginia))', max_length=255)),
                ('region_code', models.CharField(help_text='AWS region code (e.g., us-east-1)', max_length=50, unique=True)),
                ('region_id', models.CharField(help_text='Region identifier', max_length=50)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('continent', models.CharField(help_text='Continent name', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('error', 'Error')], default='pending', help_text='Location status', max_length=20)),
                ('latency_ms', models.IntegerField(blank=True, help_text='Latency in milliseconds', null=True)),
                ('last_check', models.DateTimeField(blank=True, help_text='Last health check timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['continent', 'country', 'name'],
                'indexes': [models.Index(fields=['region_code'], name='users_locat_region__ebb8d9_idx'), models.Index(fields=['status'], name='users_locat_status_26b912_idx'), models.Index(fields=['continent'], name='users_locat_contine_e54dd0_idx')],
            },
        ),
    ]
