# Generated by Django 5.2.6 on 2025-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_location_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='can_accept_jobs',
            field=models.BooleanField(default=True, help_text='Can this runner accept new jobs?'),
        ),
        migrations.AddField(
            model_name='location',
            name='cpu_load',
            field=models.FloatField(blank=True, help_text='CPU load average', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='current_jobs_running',
            field=models.IntegerField(default=0, help_text='Number of current jobs running'),
        ),
        migrations.AddField(
            model_name='location',
            name='last_lighthouse_run_sec',
            field=models.IntegerField(blank=True, help_text='Seconds since last successful Lighthouse job', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='memory_total_mb',
            field=models.IntegerField(blank=True, help_text='Total memory in MB', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='memory_used_mb',
            field=models.IntegerField(blank=True, help_text='Memory used in MB', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='runner_id',
            field=models.CharField(blank=True, help_text='Internal runner identifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('down', 'Down'), ('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('error', 'Error')], default='pending', help_text='Location status', max_length=20),
        ),
    ]
