# Generated by Django 5.2.6 on 2025-12-11 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_runner_health_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='can_accept_jobs',
        ),
        migrations.RemoveField(
            model_name='location',
            name='cpu_load',
        ),
        migrations.RemoveField(
            model_name='location',
            name='current_jobs_running',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_check',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_lighthouse_run_sec',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='location',
            name='memory_total_mb',
        ),
        migrations.RemoveField(
            model_name='location',
            name='memory_used_mb',
        ),
        migrations.RemoveField(
            model_name='location',
            name='runner_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('error', 'Error')], default='pending', help_text='Location status', max_length=20),
        ),
        migrations.CreateModel(
            name='RunnerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_id', models.CharField(help_text='Internal runner identifier (e.g., runner-usw1-001)', max_length=255, unique=True)),
                ('region', models.CharField(help_text='AWS region code (e.g., us-west-1)', max_length=50)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('down', 'Down')], default='down', help_text='Overall health status', max_length=20)),
                ('can_accept_jobs', models.BooleanField(default=False, help_text='Can this runner run Lighthouse now?')),
                ('cpu_load', models.FloatField(blank=True, help_text='CPU load average', null=True)),
                ('memory_used_mb', models.IntegerField(blank=True, help_text='Memory used in MB', null=True)),
                ('memory_total_mb', models.IntegerField(blank=True, help_text='Total memory in MB', null=True)),
                ('disk_free_mb', models.IntegerField(blank=True, help_text='Available disk space in MB', null=True)),
                ('latency_ms', models.IntegerField(blank=True, help_text='Response time to orchestrator in milliseconds', null=True)),
                ('current_jobs_running', models.IntegerField(default=0, help_text='Number of current jobs running')),
                ('last_lighthouse_run_sec', models.IntegerField(blank=True, help_text='Seconds since last successful Lighthouse job', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last health check timestamp')),
                ('location', models.ForeignKey(help_text='Associated location', on_delete=django.db.models.deletion.CASCADE, related_name='runner_health', to='users.location')),
            ],
            options={
                'verbose_name': 'Runner Health',
                'verbose_name_plural': 'Runner Health Records',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['runner_id'], name='users_runne_runner__daed4d_idx'), models.Index(fields=['status'], name='users_runne_status_eaa54e_idx'), models.Index(fields=['can_accept_jobs'], name='users_runne_can_acc_4d66c4_idx'), models.Index(fields=['location', 'status'], name='users_runne_locatio_c2d6b5_idx'), models.Index(fields=['updated_at'], name='users_runne_updated_c71dd4_idx')],
            },
        ),
    ]
