# Generated by Django 5.2.6 on 2025-12-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_separate_runner_health_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='billingtransaction',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='billingtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coinbasecharge',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='coinbasecharge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coinbasetransaction',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='coinbasetransaction',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='coinbasetransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='runnerhealth',
            name='location',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentProviderConfig',
        ),
        migrations.RemoveField(
            model_name='promotionaldeal',
            name='base_plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='promotional_deal',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='BillingTransaction',
        ),
        migrations.DeleteModel(
            name='CoinbaseCharge',
        ),
        migrations.DeleteModel(
            name='CoinbaseTransaction',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='RunnerHealth',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='PromotionalDeal',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
