# Generated by Django 5.2.6 on 2026-01-07 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tool name (e.g., OSCAL (NIST), OWASP ZAP)', max_length=100, unique=True)),
                ('tool_type', models.CharField(choices=[('api', 'API Service'), ('library', 'Library'), ('external', 'External Tool')], help_text='Type of tool', max_length=20)),
                ('sub_category', models.CharField(choices=[('frameworks', 'Frameworks'), ('automated-evidence', 'Automated Evidence'), ('manual-evidence', 'Manual Evidence'), ('policy-enforcement', 'Policy Enforcement'), ('audit-management', 'Audit Management'), ('reporting', 'Reporting'), ('continuous-compliance', 'Continuous Compliance'), ('ai-privacy', 'AI & Privacy')], help_text='Compliance tool sub-category', max_length=50)),
                ('status', models.CharField(choices=[('configured', 'Configured'), ('not_configured', 'Not Configured'), ('error', 'Error')], default='not_configured', help_text='Configuration status', max_length=20)),
                ('description', models.TextField(help_text='Tool description and purpose')),
                ('service', models.CharField(help_text='Service/Implementation name', max_length=200)),
                ('endpoint', models.URLField(blank=True, help_text='API endpoint URL (if API service)')),
                ('api_key', models.CharField(blank=True, help_text='API key (if API service)', max_length=500)),
                ('api_key_name', models.CharField(blank=True, help_text='Environment variable name for API key', max_length=100)),
                ('configuration', models.JSONField(default=dict, help_text='Additional configuration')),
                ('license', models.CharField(blank=True, help_text='License type (Apache 2.0, MIT, etc.)', max_length=50)),
                ('evidence_produced', models.CharField(blank=True, help_text='Type of evidence this tool produces', max_length=200)),
                ('repo_url', models.URLField(blank=True, help_text='Repository URL for the tool')),
                ('documentation_url', models.URLField(blank=True, help_text='Link to tool documentation')),
                ('installation_instructions', models.TextField(blank=True, help_text='How to install/configure this tool')),
                ('executable_path', models.CharField(blank=True, help_text='Path to executable (if external)', max_length=500)),
                ('command_template', models.CharField(blank=True, help_text='Command template for execution', max_length=500)),
                ('is_active', models.BooleanField(default=False, help_text='Is this tool active and ready to use?')),
                ('last_tested', models.DateTimeField(blank=True, help_text='Last time tool was tested', null=True)),
                ('test_result', models.TextField(blank=True, help_text='Result of last test')),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization ID for multi-tenancy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Tool',
                'verbose_name_plural': 'Compliance Tools',
                'db_table': 'compliance_tools',
                'ordering': ['sub_category', 'name'],
                'indexes': [models.Index(fields=['sub_category', 'status'], name='compliance__sub_cat_dec3f3_idx'), models.Index(fields=['tool_type', 'is_active'], name='compliance__tool_ty_2ae340_idx'), models.Index(fields=['organization_id'], name='compliance__organiz_da5fae_idx')],
            },
        ),
    ]
