# Generated by Django 5.2.6 on 2025-11-22 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_reports', '0002_rename_audit_repor_user_id_a1b2c3_idx_audit_repor_user_id_dda0b8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Base URL that was analyzed', max_length=2048)),
                ('links', models.JSONField(blank=True, default=list, help_text='List of discovered links with status codes, types, etc.')),
                ('total_links', models.IntegerField(blank=True, db_index=True, help_text='Total number of links discovered', null=True)),
                ('internal_links', models.IntegerField(blank=True, help_text='Number of internal links', null=True)),
                ('external_links', models.IntegerField(blank=True, help_text='Number of external links', null=True)),
                ('broken_links', models.IntegerField(blank=True, db_index=True, help_text='Number of broken links (4xx, 5xx, or 0 status)', null=True)),
                ('redirect_links', models.IntegerField(blank=True, help_text='Number of redirect links (3xx status)', null=True)),
                ('links_by_status', models.JSONField(blank=True, default=dict, help_text='Count of links by HTTP status code')),
                ('links_health_score', models.IntegerField(blank=True, help_text='Overall links health score (0-100)', null=True)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of links issues found (broken links, etc.)')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of links recommendations')),
                ('broken_links_list', models.JSONField(blank=True, default=list, help_text='List of broken links with details')),
                ('avg_response_time', models.FloatField(blank=True, help_text='Average response time for all links (ms)', null=True)),
                ('min_response_time', models.FloatField(blank=True, help_text='Minimum response time (ms)', null=True)),
                ('max_response_time', models.FloatField(blank=True, help_text='Maximum response time (ms)', null=True)),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete links analysis results')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('audit_report', models.ForeignKey(blank=True, help_text='Audit report this analysis belongs to (if part of full audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_analyses', to='audit_reports.auditreport')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Links Analysis',
                'verbose_name_plural': 'Links Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='links_analy_url_ab1842_idx'), models.Index(fields=['user', '-analyzed_at'], name='links_analy_user_id_dc1df4_idx'), models.Index(fields=['audit_report', '-analyzed_at'], name='links_analy_audit_r_f12b56_idx'), models.Index(fields=['broken_links'], name='links_analy_broken__2cdc08_idx')],
            },
        ),
    ]
