# Generated by Django 5.2.6 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='linksanalysis',
            new_name='links_analy_url_6aea32_idx',
            old_name='links_analy_url_ab1842_idx',
        ),
        migrations.RenameIndex(
            model_name='linksanalysis',
            new_name='links_analy_user_id_16c613_idx',
            old_name='links_analy_user_id_dc1df4_idx',
        ),
        migrations.RenameIndex(
            model_name='linksanalysis',
            new_name='links_analy_audit_r_4d8ebd_idx',
            old_name='links_analy_audit_r_f12b56_idx',
        ),
        migrations.RenameIndex(
            model_name='linksanalysis',
            new_name='links_analy_broken__a5749a_idx',
            old_name='links_analy_broken__2cdc08_idx',
        ),
        migrations.AlterModelTable(
            name='linksanalysis',
            table='links_analysis',
        ),
    ]
