# Generated by Django 5.2.6 on 2025-11-22 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Website URL that was analyzed', max_length=2048)),
                ('sitemap_found', models.BooleanField(default=False, help_text='Whether a sitemap was found')),
                ('sitemap_url', models.URLField(blank=True, help_text='URL of the sitemap file', max_length=2048)),
                ('sitemap_type', models.CharField(blank=True, help_text='Type of sitemap (XML, TXT, RSS, etc.)', max_length=50)),
                ('total_urls', models.IntegerField(blank=True, db_index=True, help_text='Total number of URLs in sitemap', null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Last modified date of sitemap', null=True)),
                ('change_frequency', models.CharField(blank=True, help_text='Default change frequency', max_length=50)),
                ('priority', models.FloatField(blank=True, help_text='Default priority (0.0-1.0)', null=True)),
                ('urls', models.JSONField(blank=True, default=list, help_text='List of URLs found in sitemap')),
                ('is_sitemap_index', models.BooleanField(default=False, help_text='True if this is a sitemap index file')),
                ('sitemap_index_urls', models.JSONField(blank=True, default=list, help_text='List of sitemap URLs if this is a sitemap index')),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of sitemap issues found')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of sitemap recommendations')),
                ('health_score', models.IntegerField(blank=True, help_text='Sitemap health score (0-100)', null=True)),
                ('full_results', models.JSONField(blank=True, default=dict, help_text='Complete sitemap analysis results')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this analysis was performed')),
                ('user', models.ForeignKey(blank=True, help_text='User who ran this analysis (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitemap_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sitemap Analysis',
                'verbose_name_plural': 'Sitemap Analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['url', '-analyzed_at'], name='sitemap_ana_url_3b42f2_idx'), models.Index(fields=['user', '-analyzed_at'], name='sitemap_ana_user_id_b05c5f_idx'), models.Index(fields=['sitemap_found'], name='sitemap_ana_sitemap_c9b06a_idx')],
            },
        ),
    ]
