# Generated by Django 5.2.6 on 2025-11-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap_analysis', '0002_sitemapanalysis_audit_report_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitemapanalysis',
            new_name='sitemap_ana_url_bb4fac_idx',
            old_name='sitemap_ana_url_3b42f2_idx',
        ),
        migrations.RenameIndex(
            model_name='sitemapanalysis',
            new_name='sitemap_ana_user_id_81122a_idx',
            old_name='sitemap_ana_user_id_b05c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='sitemapanalysis',
            new_name='sitemap_ana_audit_r_77dba8_idx',
            old_name='sitemap_ana_audit_r_f3d2e6_idx',
        ),
        migrations.RenameIndex(
            model_name='sitemapanalysis',
            new_name='sitemap_ana_sitemap_373596_idx',
            old_name='sitemap_ana_sitemap_c9b06a_idx',
        ),
        migrations.AlterModelTable(
            name='sitemapanalysis',
            table='sitemap_analysis',
        ),
    ]
